### ISSUE TITLE
Conbee updated!

### ISSUE THREAD

**Issue by Fl0ca** [dresden-elektronik/deconz-rest-plugin#1092]
Hi everyone, 
regarded to the update problems with a virtual machine and the conbee, is it possible to write down a note in the changelog that there was an update for the Conbee?

Is there an update in the new .54 release?

**Comment by manup** [comment]
Good hint, next release notes will contain the included firmware version. The latest version in the package is 0x262f0500.

Since 2.05.54, when used with Docker, the update button in Phoscon App won't be shown only a hint that an update is available. Same is true for firmware updates.

In near future GCFFlasher will be updated so that firmware updates inside VMs and Docker become way more easy.
