### ISSUE TITLE
Web App - where is it?

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#1093]
After updating the firmware I can no longer get to the Web App, even when clikcing the button on deConz. It always takes me to Phoscon.  I liked the dashboard of the Web App, it was much nicer and easier to use/see all groups on the same page.

thx

**Comment by wvuyk** [comment]
Manup

Am I right assuming that once the old webapp is gone we can reset Philips bulbs only with the Hue dimmer? The touchlink will not appear in Phoscon?

**Comment by manup** [comment]
The old webapp will stay for a while, there are no plans yet to remove it and Touchlink is one reason for that. What will be removed or disabled in the mid future is the ability to add/configure switches in the old webapp, since this causes some issues with the Phoscon App.

>The touchlink will not appear in Phoscon?

Maybe, but currently there are no plans.

Note that the feature is also available via REST-API and could be used by third party apps.

http://dresden-elektronik.github.io/deconz-rest-doc/touchlink/

**Comment by wvuyk** [comment]
@manup 
Yes, maybe you are right there. Had it for Philips Hue bridges in the plugin, but never worked on that for deCONZ. But with bulbs resetting without remotes it might be better to have it in place... Already users buy a Philips bulb, but do not have the Hue dimmer with it.

Thanks!

**Comment by ebaauw** [comment]
Note that you now need to power cycle the Hue bulbs, for touchlink to work.  Since the Nov 2017 firmware, they only respond within 30 minutes after powering on.

**Comment by wvuyk** [comment]
That is no problem, I can include that in instructions for the plugin. Thanks for reminding me :-)
