### ISSUE TITLE
Slow reporting of movement

### ISSUE THREAD

**Issue by phdelodder** [dresden-elektronik/deconz-rest-plugin#1178]
I have been using the 2.05.57 since the release with deconz-docker. I have noticed a delay after 24 - 36 hours running of the deconz application. To resolve this I have to restart the container and all works well everything is reported instandly. I only have aqara motion sensors and aqara door/window sensors. 

I changed version back to 2.05.55 as it is not ideal to restart every now and then.

**Comment by saxn-paule** [comment]
I can confirm this. My Aqara motion sensor only triggers in one out of ten situations. With .54 everything worked fine.

**Comment by manup** [comment]
>I have noticed a delay after 24 - 36 hours running of the deconz application.

How long is this delay?

And what is the receiver side aka where are the events processed?

> My Aqara motion sensor only triggers in one out of ten situations. With .54 everything worked fine.

The processing of motion signal and firing the event, hasn't changed. But maybe since we refresh the `state.lastupdated` attributes (since 2.05.57) in the hourly reports, it influences firing of events.

I'll make some tests before 2.05.58 release.

**Comment by rich710se** [comment]
I can confirm this also, about half of the times when i go in front of aqara motion sensor, it trigger the light immediately, but 15 minutes later when i pass it doesn't. Can't nail it to any specific cause.

**Comment by phdelodder** [comment]
@manup The delay is about 1 or 2 minutes. I first thought it was Home Assistant, but I see the same behavoir in phoscon app.

**Comment by manup** [comment]
>@manup The delay is about 1 or 2 minutes. I first thought it was Home Assistant, but I see the same behavoir in phoscon app.

Hmm the above mentioned problem likely plays a role here.
But also note for the Xiaomi motion sensor the minimum delay between two motion signals is always **at least** 60 seconds. This is likely to not drain the battery.

Only during setup phase the sensor triggers in smaller time intervals for a while (minutes?).

**Comment by manup** [comment]
Which version is shown for the sensors?

If possible can you please provide the REST-API output of the sensor.

**Comment by wvuyk** [comment]
I can also confirm this issue. It has been for a few versions. it is not consistent, on time the response is send immediatly, another moment there is a delay of 1 to 2 minutes. Hve not been able yet to check the status in deCONZ compared to the REST API.... will try that when possible

**Comment by phdelodder** [comment]
How can I provide the rest output? I only use it in combination with home assistent.

**Comment by manup** [comment]
@Kane610 can you provide a hint, any debug log option?

**Comment by Kane610** [comment]
For the component? Sure, follow debug instructions here https://www.home-assistant.io/components/deconz/

**Comment by wvuyk** [comment]
Hmm, checked here on my installation, but duration is set to 60. Never changed it here, so it might have been set by an old default maybe? Changing it here to 90 now.

`ZHAPresence

**************************** Object info *****************************
{
"state": {
"presence": false,
"lastupdated": "2019-01-26T09:56:36"
},
"config": {
"on": true,
"battery": 100,
"duration": 60,
"reachable": true
},
"name": "Slaapkamer Motion",
"type": "ZHAPresence",
"modelid": "lumi.sensor_motion.aq2",
"manufacturername": "LUMI",
"swversion": "20170627",
"uniqueid": "00:15:8d:00:01:e5:62:85-01-0406",
"ep": 1,
"etag": "a9b820c323ede233abe2d9f8846cb697"
}
************************* End Object info ***************************
`

**Comment by manup** [comment]
Yes 60 is the default until version 2.05.57. Starting with 2.05.58 it will be 90 for Xiaomi motion sensors, already paired sensors will be raised to 90 if the value is < 90.

In my sniffer logs the time between two signals with constant motion is often > 60 more like 70, 80 hope the 90 seconds default will smooth the rough corners.

**Comment by phdelodder** [comment]
So 90 seconds, means reworking automations? 

My version is 20170627

**Comment by manup** [comment]
Hard to tell, can you please provide a example of your automations using the sensor?

The 90 seconds is more a internal change to ensure the presence: false state isn't set too early.

**Comment by chimpy** [comment]
2 cents: My Xiaomi motion sensors on 2.05.57 are working perfectly with HA. Instant motion reporting, sane `presence: false` reporting.

**Comment by phdelodder** [comment]
@chimpy for me it's also working perfectly for the first 24hours, after that I moments where it is from 1 to 2 minutes before motion is visible in HA or phoscon.

**Comment by tubalainen** [comment]
+1 on a bit longer delay with the latest release.
However, for me it is not that bad. The delay for me can be up to 2-3 seconds at worst.
The "longer the mesh" the more delay.

Ive got 16 IKEA bulbs/drivers and 2 Philips hue and 5 IKEA motion sensors.

**Comment by phdelodder** [comment]
With the new update I was forced to restart deconz after 38 hours because the Xiaomi motion sensor where not reporting motion. Restarting resolved it. I will try to get the log when it reoccurs.

**Comment by kugelkopf123** [comment]
I had a similar feeling with my PIR Aqara sensors. Could, however, find that they continue to change the LUX value but not the presence value. There it took partly over 3 minutes before this new values took over. However, I could not find any regularity. Sometimes it took 6 minutes sometimes only 1min.

What exactly is wanted?
Should the precence value be true as long as there is movement in front of the device?
Because currently he is triggered, stays 12sec. true and then goes to false. It will take 90 seconds or more for the next trigger "True". And so on.

I do not know if I solved the problem. A few days ago I deleted all PIR sensors and added a few times and then deleted and added again.
At the moment I am still at .57

**Comment by phdelodder** [comment]
The log was cut off. The restart was around 6u6

**Comment by phdelodder** [comment]
You are correct, I don't have any lights in the my network at this time. 

I only have Xiaomi battery devices.

**Comment by M203** [comment]
One of my Xiaomi motion sensors has started to report motion with hefty delay or not at all. When stepping in front of the sensor it always reports lux instantly. I really dont understand what is the problem. 

Running 2.05.58 Home assistant addon. My RPI crashed the other day and this started after setting everything back up again. Home assistant backup and Phoscon backup was used. I have tried removing and readding the sensor to deconz. Same behaviour.

**Comment by saxn-paule** [comment]
In the phoscon GUI the lux value is updated every 60 seconds. The movement never.

**Comment by M203** [comment]
So, pulled the battery of the xiaomi motion sensor in question. Let it lay around for a while, turned off power for three tradfri lights just beside it. put the battery back, readded in phoscon. So far it seems it sends presence as expected.

**Comment by M203** [comment]
So, a couple of hours later old behaviour with delat in motions sensor reporting or no reporting at all is back. Note that this sensor worked flawlessly before I had to reinstall everything due to sd failure.

**Comment by manup** [comment]
2.05.59 is available now, can you please check if sensor behaves better.
The issue might be related to the high cpu load problem of 2.05.58.

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_59

**Comment by phdelodder** [comment]
@manup Upgraded the docker-deconz, running the new version already. Will monitor the situation and keep you posted!

**Comment by saxn-paule** [comment]
After updating to .59 everything worked well again......for aprox. one day. Scince yesterday no motion is detected at all.

I will restart the deconz service today in the evening and check if this helps.

CPU load is normal, ~5-7% (Pi 3)

**Comment by phdelodder** [comment]
I'm seeing the same result, yet the entire pi was locked up. Had to pull the power to restart it, don't know whats the reason, also don't have any logs. 

@saxn-paule do you have any logs?

**Comment by saxn-paule** [comment]
No, I don't have any logs. My Pi works as expected and all other sensors, lights, switches respond as usal. Only the motion sensor is buggy since the update from .54 to .57

**Comment by manup** [comment]
@saxn-paule have you tried to delete the sensor and rejoin it, in order to create a default configuration?

**Comment by saxn-paule** [comment]
No, but I will do it today.

**Comment by saxn-paule** [comment]
I deleted and readded the sensor without restarting deconz. It works again. We will see, how long.

The device IDs differ from the old ones.

**Comment by saxn-paule** [comment]
After repairing the sensor it works flawless since one week now.

**Comment by mwegner** [comment]
Like others, the recent changes to Xiaomi motion sensor handling have negatively impacted my responsiveness.  Firstly:  **Is there some way to get the now-suppressed motion event in Home Assistant**?  I don't see anything coming across the HA event bus in deconz_event, and I'm not sure where else to look.

A couple of thoughts:

- In general, looking at a motion sensor's binary state has never worked well for me.  Motion sensors are great for knowing when someone enters a room, but not so great at detecting when someone leaves a room.  I run all of my room on/off logic with my own _off_ timers, and only look at any given motion sensor's _on_ trigger (zigbee or otherwise).

- Let's say Xiamoi sensors re-triggered in 60-90 seconds.  The old threshold was the minimum end of that range--so every time they triggered, they were _guaranteed_ to send out their state downstream (to i.e. home assistant).  The downside here is they would flap state to off.

- But now, the threshold is at the high end of that range.  _If there is continuous motion in a room, there will **not** be a state change sent to other systems_.  I had room lights turn off on me since the update, which is a 10 minute timeout.  I was pretty confused by that until I saw this thread.

I guess the change was to support directly tying a motion sensor's state to i.e. lights within Phoscon natively?  But to be honest, I doubt many people are doing that--and instead using Home Assistant or other larger ecosystems.

I don't mind the change if there's some way I can alter my automation to still detect the re-trigger.  But it seems that Deconz is now just silently extending an internal timeout?

**Comment by chimpy** [comment]
9 motion sensors here, using the binary state from HA with Node Red. No complaints, everything works as expected.

If there is continuous movement then the binary state stays on.

I only use `deconz_event` with the Xiaomi switches, but it's found in `event_type`.

**Comment by mwegner** [comment]
Yeah, I get that it's the binary state that's been extended by a timeout.  It breaks my use case, though, which is aggressively turning off rooms that I'm not in.  I live alone, and my automation has a "home alone" mode that does things like--if there's mouse/keyboard activity in the office, turn off all other rooms.

This change means that you _have_ to use the binary state of the sensor to determine room on/off state.  But the side effect there is you can't turn off a room manually anymore, because you can't update the state yourself.

Now, if I turn off a room with a Deconz-handled Xiaomi sensor, there's a new ~20-30 second window where it will be nonreponsive, where before it would report a state change.  This period repeats every 90 seconds (the timeout), so there's basically a ~30% chance you get a nonresponsive sensor for quick room-to-room activities.

I could turn some of my "turn room on" triggers that don't have binary states _into_ binary states, to try to merge, but that's not as easy as it seems at a glance.  (These are RF motion sensors, turning on a room from contacts opening, etc).  It also doesn't fix the issue of being unable to turn off a room if any of those states are considered on.

Honestly, I think it's just backwards implementation logic, and the timeout should always be _less_ than the earliest possible report, not more.  Motion sensors should really be though of as:

- "Off, waiting for motion"
- "On, recent motion detected, cooling down"

Extending an internal timeout becomes "silently suppress a state change for 90 seconds", which is really bad if you use them as triggers.  Maybe it's just affecting me more because I regularly walk through rooms I've just turned off, though.

**Comment by chimpy** [comment]
I still don’t understand. If you turn off the light when the binary state change “off” is reported you will not have any chance of an unresponsive sensor.

**Comment by mwegner** [comment]
I turn a room off when the motion state is still true.  Sequence of events is:

- Walk from kitchen to office.  Kitchen motion is on, living room motion goes to on, etc

- Touch computer in office.  Automation turns off other rooms (kitchen, living room).  At this point, binary state for motion sensors is likely still true for a short window

- I get up and go back to kitchen for something I forgot

Quick back-and-forth like this always has issues, and I'm used to a room staying dark for a few seconds if I immediately double back after something turns it off.

But now, there's a new problem with a 20-30 second trigger window (the difference between the hardware minimum report time and 90-second extended timeout) introducing a really bad hole where if I _do_ trigger the motion sensor that quickly, it's going to suppress any state change for another 90 seconds by staying true.  From the point of view of my automation, a state change that would have occurred no longer happens.  And using the binary state alone won't help this, because of the manual room turn-off while binary state is true anyway.

I need one of two options:

- A raw event fired, even if the internal logic is just extending a timeout (I'll check into event_type, but from a quick glance at the codebase here I think that will only trigger if Deconz states change, and based on my understanding of the timeout, it won't)

- A way to manually change a motion sensor's Deconz state to false (which maybe you can do now?  I haven't looked at the direct REST API options)

**Comment by chimpy** [comment]
What happens if you manually the the state in HA?
Sequence:
- your motion sensor triggers
- you immediately set the motion sensor to “off” on HA’s Set States page
- wait 60s
- you walk past the motion sensor

Does the motion sensor go back to “on”?
If so you can solve your problem including an HA API call to set the motion sensor manually to “off” when you run your “touch the computer” automation.

**Comment by ebaauw** [comment]
> Extending an internal timeout becomes "silently suppress a state change for 90 seconds"

No.  Granted, `state.presence` remains `true`, but `state.lastupdated` is updated when the new motion event arrives.  You should trigger your automations on that attribute.

**Comment by mwegner** [comment]
> > A raw event fired, even if the internal logic is just extending a timeout
> 
> That would be the change to `state.lastupdated`, but I don’t know if/how HA handles this.

It doesn't appear to be handled at all, unfortunately.

![screen shot 2019-02-28 at 9 27 14 pm](https://user-images.githubusercontent.com/271924/53616536-4a5e2200-3ba0-11e9-81ef-a6c39cb72b78.png)

In this screenshot, the bottom window is a websocket debug tool connected directly to Deconz.  The top window is showing the Home Assistant log set to debug.  The timestamps make it easier to see what's going on.

You can see the `lastupdated` push from Deconz, but nothing from HA.  I'm not super familiar with the HA innards, but at glance, I guess it's probably dying here: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/deconz/binary_sensor.py#L53

Those logs in text form:

```
2019-02-28 21:25:05 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=binary_sensor.office_motion, old_state=<state binary_sensor.office_motion=off; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:24:44.565010-07:00>, new_state=<state binary_sensor.office_motion=on; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:25:05.544155-07:00>>
2019-02-28 21:25:05 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139777901623504] Sending {'id': 88, 'type': 'event', 'event': {'event_type': 'state_changed', 'data': {'entity_id': 'binary_sensor.office_motion', 'old_state': <state binary_sensor.office_motion=off; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:24:44.565010-07:00>, 'new_state': <state binary_sensor.office_motion=on; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:25:05.544155-07:00>}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2019, 3, 1, 4, 25, 5, 544189, tzinfo=<UTC>), 'context': {'id': 'c16201c2c42f4f7a97f71fc1cd14cef0', 'user_id': None}}}
2019-02-28 21:25:05 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139777901866960] Sending {'id': 2, 'type': 'event', 'event': {'event_type': 'state_changed', 'data': {'entity_id': 'binary_sensor.office_motion', 'old_state': <state binary_sensor.office_motion=off; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:24:44.565010-07:00>, 'new_state': <state binary_sensor.office_motion=on; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:25:05.544155-07:00>}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2019, 3, 1, 4, 25, 5, 544189, tzinfo=<UTC>), 'context': {'id': 'c16201c2c42f4f7a97f71fc1cd14cef0', 'user_id': None}}}
2019-02-28 21:25:05 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139777901866960] Sending {'id': 3, 'type': 'event', 'event': {'event_type': 'state_changed', 'data': {'entity_id': 'binary_sensor.office_motion', 'old_state': <state binary_sensor.office_motion=off; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:24:44.565010-07:00>, 'new_state': <state binary_sensor.office_motion=on; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:25:05.544155-07:00>}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2019, 3, 1, 4, 25, 5, 544189, tzinfo=<UTC>), 'context': {'id': 'c16201c2c42f4f7a97f71fc1cd14cef0', 'user_id': None}}}
2019-02-28 21:25:05 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139777902865376] Sending {'id': 2, 'type': 'event', 'event': {'event_type': 'state_changed', 'data': {'entity_id': 'binary_sensor.office_motion', 'old_state': <state binary_sensor.office_motion=off; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:24:44.565010-07:00>, 'new_state': <state binary_sensor.office_motion=on; battery_level=100, on=True, friendly_name=Office Motion, device_class=motion @ 2019-02-28T21:25:05.544155-07:00>}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2019, 3, 1, 4, 25, 5, 544189, tzinfo=<UTC>), 'context': {'id': 'c16201c2c42f4f7a97f71fc1cd14cef0', 'user_id': None}}}
```

```< {"e":"changed","id":"3","r":"sensors","state":{"lastupdated":"2019-03-01T04:24:44","presence":false},"t":"event","uniqueid":"00:15:8d:00:01:e5:61:6a-01-0406"}
< {"e":"changed","id":"3","r":"sensors","state":{"lastupdated":"2019-03-01T04:25:05","presence":true},"t":"event","uniqueid":"00:15:8d:00:01:e5:61:6a-01-0406"}
< {"e":"changed","id":"3","r":"sensors","state":{"lastupdated":"2019-03-01T04:26:12","presence":true},"t":"event","uniqueid":"00:15:8d:00:01:e5:61:6a-01-0406"}
```

I seriously do appreciate the continuous development effort behind Deconz, but I don't understand this change all that well.  To support tying i.e. turning lights off directly to a single motion detector presence flag?  That's never going to work in practice (no single motion detector in any of my rooms sees me all the time; the lights would turn off constantly).  I'm very curious who was seeing bad behavior from the old defaults?

It feels a lot like a very pedantic "these numbers aren't quite lined up right" change, but it's having side effects I can't work around.  The real world impact here is that if I re-trigger a Xiaomi motion detector inside that 0:60-0:90 window, I now have to wait another 90 seconds, _without triggering it again_, before it sends any data to my Node-RED automations via Home Assistant.

For what it's worth:  If I can find some time this weekend I'll try to fix it at the HA level and do a PR.

**Comment by carloscae** [comment]
Hi guys, is there a way to reduce Hue refresh rate? 
Via Conbee it updates every 60s, while on Hue it does every 10s.
