### ISSUE TITLE
IKEA Trådfri light bulb turned on by itself

### ISSUE THREAD

**Issue by mwhrtin** [dresden-elektronik/deconz-rest-plugin#1186]
Running deCONZ 2.05.55 and Rest API 1.16.0 together with HomeAssistant.

**Issue:**
One of my IKEA Trådfri bulb E27 CWS opal 600lm was turned on by itself. 4 minutes after it was turned off through the Rest API it turned on without any manual/automatic interaction or anything sent over the Rest API.

I'm not sure if this is a deCONZ or IKEA Trådfri issue, but perhaps some one here knows what might have happened and why?

**The long description:**
I have three IKEA Trådfri lights connected to deCONZ (nothing else), two of the lights are located in the same room if that matter. I turned off the two lights located in the same room, one of them using the power switch and then I turned off both of them through the Rest API. 

I could see in the HomeAssistant logs that the deCONZ Rest API sent websocket events about turning the lights off and also that they were actually turned off with received change events `"state.on": false`.

After 3 minutes the Rest API sent a `"reachable: false"` event for the light that was powered off, this was expected since it was no longer reachable. 

But 4 minutes after the lights changed to `"state.on": false` the light that was only turned off was turned on again. In the HomeAssistant logs there was a received change event`"state.on": true` sent over the websocket but nothing else. So it was nothing sent over the Rest API that told the light to turn on and no rule existed in the Rest API that would turn on the light.

So either deCONZ or the light bulb itself decided that it should be turned on again.

**Comment by Ronoon** [comment]
Happend yesterday evening to my Innr GU10 Bulbs used with motion sensors also.
After they were off since the timing was done  about 2-3 minutes later they turned on with 100%. Shutting them down manually with override by Hue four button switch to off state.
About 6 hours later same game happend again. As long i couldn´t find a problem or solution to this behavior. Running a Raspi 3B with original ZigBee Aufsatzmodul mit Firmware 262F0500 and DeConz 2.05.57 
Other then that i also can see that the load on the Raspi is increasing over the day since the update to .57 as it is known on other issues and should be fixed by Manuel with the next version. 
So i think we have to wait to the .58 version and see if this was a temporary bug or should be more investigatet by Manuel

**Comment by snarby2013** [comment]
I am having the same issue, I have nine gu10 Ikea bulbs in the kitchen and they have been switching on themselves the last few days. It also seems to be exactly an hour each time although its random when I reboot. Yesterday it was 25 minutes past the hour and today its on the hour exactly. I can't seem to find any logical reason why

**Comment by manup** [comment]
There is one known bug for Ikea lights that they will turn on when they are added or removed to a group. Not sure if it is related here.

If there is a motion sensor involved, we might also track if it did trigger. Sometimes motion sensors can trigger due low battery; or when the air temperature is changing/moving, like when a warm room is next to an unheated room and air flows between them.

**Comment by snarby2013** [comment]
I have checked within Home Assistant and no motion was detected.
I have just read about the ghost push issue that was fixed in the last week and forgot to say that I have also recently added the round Xiaomi button although the only place it is linked is within Deconz (not Home Assistant).
I am hoping it may be related to this as from what I can tell this is related to Xiaomi devices hourly report which would explain why its exactly an hour each time

**Comment by snarby2013** [comment]
It has been working great up to now for several months as well!

**Comment by snarby2013** [comment]
I disabled the switch last night and its no longer happening so definitely related to this issue #1165

**Comment by manup** [comment]
Is the problem still occurring with latest release 2.05.59?

**Comment by snarby2013** [comment]
It was fixed for my issue in 2.05.58 so was related to the switch

**Comment by manup** [comment]
>It was fixed for my issue in 2.05.58 so was related to the switch

Ok yes the Xiaomi Mi devices should now work without these side effects.

There is one other case when IKEA lights turn on unwanted: When the light is off and the group membership is edited (add/remove), the light turns on. But this is a bug in the light firmware it self.

Closing this issue for now.

**Comment by istepaniuk** [comment]
I have 4 IKEA Trådfri GU10 lights that are grouped and always turn on and off together. One of the bulbs turns on by itself, randomly (once every few days). I was on DeConz  2.05.57 and now upgraded to the `:latest` docker image (2.06.00). Combee II firmware is 264A0700. Hopefully this goes away.... I do have Xiaomi devices but none is related to these lights whatsoever.There is only one Trådfri simple switch linked to the group.

**Comment by StanWijn** [comment]
I recently updated to 2.06.00 and am experiencing this problem as well. My Ikea Tradfri lights suddenly turn on 15-30 minutes after we turned them off. We do not have sensors and use home assistant to turn the lights off.

**Comment by jsa91** [comment]
Same here. Running Home Assistant 2020.12.6 with deCONZ 2.7.1. I have no sensors installed and one of my Ikea light bulbs turned on automatically last night. Any tips here?
