### ISSUE TITLE
Door/Window sensors and group cluster

### ISSUE THREAD

**Issue by stevenwfoley** [dresden-elektronik/deconz-rest-plugin#1316]
Does anyone have any experience with a door/window contact sensor that supports the Groups cluster? I'd like to have my door sensors operate if the phoscon gateway is down.

**Comment by stevenwfoley** [comment]
I bought an Xiaomi Aqara MCCGQ11LM window/door sensor, and it seems to support the Groups cluster. I think this because there is an item named "Groups" in the Cluster Info dialog for the device in deconz. Does anyone know how to take advantage of or configure this groups cluster with a sensor?

**Comment by manup** [comment]
The Groups cluster is a client side (grey color), usually this is used so that the sensor could control group membership of other devices, like put a light to a specific group.

![image](https://user-images.githubusercontent.com/383386/56792313-9a0c4300-6809-11e9-9093-d1c69883964d.png)

I can only image the only way to get the sensor work when the gateway is offline is a binding from the On/Off cluster to a group. 

![image](https://user-images.githubusercontent.com/383386/56792811-c2e10800-680a-11e9-81e5-7b08d944348f.png)

Unfortunately this doesn't seem to work, the binding can be created but sensor still just reports to the gateway. Also tried with unicast binding to a IKEA light but still the sensor only reports to the gateway.

**Comment by stevenwfoley** [comment]
Thanks for trying manup.
