### ISSUE TITLE
[Request device support] Gledopto GL-S-007Z

### ISSUE THREAD

**Issue by wrenchse** [dresden-elektronik/deconz-rest-plugin#1348]
Relating to this issue:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1284
Pasting in contents below

The Gledopto Soposh Dual White and Color GU10 spotlights are added as two lights.
Color works fine, but using color temperature, the lights turn off whenever brightness is set using either of the lights.

The first light added, with Vendor GLEDOPTO, does no even allow to switch to color temp mode. The other light, Vendor: Unknown, does allow for color temp.

Setting the color temperature works as intended, but touching brightness turns the light off. If then changing color temp the light will turn back on at the correct brightness.

My theory is that since the first of the two lights lacks the color temp mode, the brightness change of the other lamp will set the first one to 0.

Note this is using Phoscon. Let me know if you want me to check something in the cluster-view.

Hue hub v2 handles these spots correctly, which is the only reason I still have a hue hub lying around. I also have have a Soposh E27, unsure what the model number is, but that bulb has the same issue.

Cluster info Basic shows the same on both ZLL and ZHA endpoints.

![Screen Shot 2019-03-12 at 10 35 50](https://user-images.githubusercontent.com/6579112/54195691-a89fd480-44bf-11e9-92cd-414e41b74429.png)
![Screen Shot 2019-03-12 at 10 36 39](https://user-images.githubusercontent.com/6579112/54195696-ac335b80-44bf-11e9-869e-817e1dec1c19.png)

I am running Deconz in a Hassio addon and could only view a small section of the logs. I quickly reproduced the issue described and switched over to grab the logs so it should be contained there.
[log.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2956531/log.txt)

Let me know if I can be of any more help.

**Comment by ebaauw** [comment]
> The Gledopto Soposh Dual White and Color GU10 spotlights are added as two lights.

According to the information I got, the GL-S-007Z is an RBG+CCT light, just like the GL-C-008 (see #1205).  It supports 5 channels (R, G, B, CW, WW) from one endpoint.  Only either the R, G, B or the CW, WW channels are active at any time.  When you set a colour, the RGB channels are activated, when you set a colour temperature, the CW and WW channels are activated.

This looks like one of those model variants that expose the same functionality twice, once on a ZLL _Extended Color Light_ endpoint and once on a ZHA _Color Dimmable Light_ endpoint.  I never got my hands on one of these, but I suspect the Hue bridge only exposes the ZLL endpoint as `/lights` resource.  You can check what `uniqueid` the Hue bridge exposes: I suspects it ends in `-0b`.  The deCONZ REST API exposes the both endpoints as separate `/lights` resources.

> The first light added, with Vendor GLEDOPTO, does no even allow to switch to color temp mode. The other light, Vendor: Unknown, does allow for color temp.

Can you please check what `uniqueid` is associated with the `GLEDOPTO` and what with the unknown vendor?  I suspect the resource for the ZLL endpoint supports colour temperature, whereas the resource for the ZHA endpoint does not.  Additionally the `type` should reflect which resource is which endpoint.  Or better yet, can you list the REST resources for the light?

I think there's a design flaw in deCONZ that the ZCL values are stored per node, rather than per endpoint, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1204#issue-405725043, bug 1.  I've only observed this on the RBGW models (that expose R, G, B on an _Extended Color Light_ endpoint and W on the another _Dimmable Light_ endpoint - allowing all four channels to be active simultaneously), but I'm guessing it might play a part here.  To rule that out, could you (temporarily) disable the REST API plugin (from the plugins menu in the GUI).  Then, could you read the attributes of the _Basic_ and _Color Control_ clusters on both 0B and 0C endpoints, and post screenshots of the four of them?

> My theory is that since the first of the two lights lacks the color temp mode

I don't think it does, but that should be confirmed by the _Color Capabilities_ attribute (0x400A), so please take multiple screenshots of the _Color Control_ cluster, covering all attributes.  I suspect the REST API plugin might actually suppress the `state.ct` attribute on the _Color Dimmable Light_ ZHA endpoint, even though the spot supports it.

> the brightness change of the other lamp will set the first one to 0.

I do think it's related to deCONZ confusing the endpoints.  Still with the REST API plugin disabled, using the clusters in the ZLL endpoint, could you, in the deCONZ GUI, turn the light on (_On/Off_ cluster), set a colour temperature (_Color Control_ cluster) and try and change the brightness (_Level Control_ cluster).  Please try different commands, _Move to Level_ and _Move to Level (with on/off).  My guess/hope is that both should work.  If yes, could you re-enable the REST API plugin, wait for it to start polling the lights (check deCONZ log), and retry this sequence (from the deCONZ GUI).  If that doesn't work, it's probably related to the ZCL values bug.  If it doesn't work while the REST API plugin is disabled, there's likely a limitation of the bulbs firmware.  Please try to figure out of it's the _Move to Level_ or the _Move to Level (with On/Off)_ causing the light to switch off.

If you're still with me, please redo the previous paragraph for the ZHA endpoint.
