### ISSUE TITLE
Support for philips living whites plug

### ISSUE THREAD

**Issue by Krocko** [dresden-elektronik/deconz-rest-plugin#140]
Any chance to support the Philips living whites plug?

**Comment by manup** [comment]
We tried that but it's not possible since the living white devices (all of them including lights and remote) don't join normal ZHA/ZLL networks. They are pre hue products using a security key only known to Philips, which is why they could (can*) be paired to hue bridge.

As alternative OSRAM and Busch Jaeger do offer plugs which work with deCONZ (at least in Europe).

**Comment by Krocko** [comment]
Ok. Thank you for your answer.

**Comment by manup** [comment]
I close this for now, since the living white devices can't be integrated due the mentioned problems.
