### ISSUE TITLE
Migration from Conbee to Conbee II

### ISSUE THREAD

**Issue by steeriks** [dresden-elektronik/deconz-rest-plugin#1441]
Hi,

What is the recommended way to migrate from Conbee to Conbee II?
I asume I have to reset all devices and repair it with the new gateway. Or is there an easy way to do it?

**Comment by manup** [comment]
>I asume I have to reset all devices and repair it with the new gateway.
This for sure is the most clean way.

There is one simpler way (cloning).

**Two important notes:**

1. There is no Zigbee related technical advantage in replacing ConBee with ConBee II
2. After the following cloning procedure the ConBee **can't be used** next to ConBee II since they are clones on Zigbee level and would fight each other. This can only be fixed by assigning a new or random mac address in deCONZ.

### Cloning 
* Pull out the ConBee and replace with ConBee II (must be on the same machine).
* In the Phoscon App gateway settings open the hidden Zigbee configuration page and load the last configuration, this is shown in the following release notes

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_59

After this ConBee II should use the same Zigbee network parameters as the setup of the ConBee.

**Comment by steeriks** [comment]
Thanks, 

will make it a try :-)

**Comment by ooii** [comment]
Hi,

`Pull out the ConBee and replace with ConBee II (must be on the same machine).` is that supposed to be done while deConz is running?
