### ISSUE TITLE
Reactivating #1122 about multiple endpoints

### ISSUE THREAD

**Issue by Hex-3-En** [dresden-elektronik/deconz-rest-plugin#1617]
Hey guys, just asking to clarify the content from #1122:
- deLightSwitch: all events pushed on main resource, but also has additional resources on API per endpoint
- busch-jaeger & innr rc110: events spread to resource per endpoint, currently not collected on main resource
- ubisys : collected as one resource per switch, only one exposed on API

- upcoming switches will be exposed like the ubisys, but will contain config.groups to determine which groups (one per endpoint) they are in.

@ebaauw @manup anything wrong up to this point?

if this is correct:
- is there an easy way to identify the main resource on e.g. a busch-jaeger switch, to catch it and ignore the others, like a static endpoint number that is always the first one?
- as the busch-jaeger only tell "RB01" or "RM01" for modelid, is there an easy way to determine how many buttons it has or do i have to request the corresponding group for figuring this out?

I'm asking this as I'm currently back into the openhab deconz binding rewrite, and would like to support as many switches as possible in the best way possible to have the easiest usage possible from within openhab and I therefore want to create one "thing" to represent one physical device and set standardized "channels" for the buttons so the switches and sensors can support the prebuilt functionalities of the openhab-framework without too much tinkering by the users.

Danke im Voraus und sonnigen Gruß aus Lübeck 😉

**Comment by ebaauw** [comment]
The code to expose the RC 110 as one REST endpoint should still there, commented out.  Happy to re-activate it, but I got errors somewhere (sorry, it’s been a while) because multiple values in `/config/group` weren’t understood.  We really should be implementing the `capabilities` for switches, like the recent versions of the Hue API, so deCONZ REST API clients no longer need to whitelist switches for supported buttonevents.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/974#issuecomment-489426415
