### ISSUE TITLE
Xiaomi Window Door Sensors Motion Sensor loose connection Aquara Magic Cube appears not as switch in the configuration

### ISSUE THREAD

**Issue by ollimagic** [dresden-elektronik/deconz-rest-plugin#1854]
Since Update to the last Version in my Hassio Raspberry 3B Configuration with  RaspBee
and in a test onfiguration with Conbee 2 Stick same problems

**Comment by silent-303** [comment]
Same here:
I am running 2.05.69 on Raspberry 3B / RaspBee and could install the Cube which shown as:
Hersteller Xiaomi
Produkt ZauberwürfelMFKZQ01LM
Version 20160704
Zustand 7000

But it is not shown as switch in a lightning group, only under "devices"

**Comment by silent-303** [comment]
[SOLVED] In previous releases the Xiaomi Cube was sometimes not paired completely (with two sensor resources). In such cases you would need to repair the cube. You can see that the cube is fully paired when the switch details show both, the button event as well as the rotation angle.

**Comment by ollimagic** [comment]
ok and how do i repair the cube 
i already tried everything connect it again move turn rotate during peering
nothing helped

**Comment by silent-303** [comment]
Hello,
i did a long press until the blue led stays on and then pressed serval times. I needed more trys, it is a bit tricky to get it conneckted.
Btw. i did connected it as a "Sensor", maybe this makes the difference ?! Readed it somewhere...

**Comment by sysadmama** [comment]
Hi,

I read about the incredible new features in `2.05.67`, so I had to immediately try... I reconnected my Aqara since it was mostly useless so far ;) It was a bit tricky, but now I have a switch device presenting  rotation angle and button event (and they are updating accordingly btw).

```
62.48° / 1002
```

But it's not possible for me to use it, because I can't assign it to a group: it's still **not** listed under *available switches* oO Might it be the cube's version (name of the switch makes no difference)?

![Screen Shot 2019-11-10 at 13 11 32](https://user-images.githubusercontent.com/11242139/68543748-b5acf480-03bb-11ea-8784-61f4097d4b21.PNG)

Would be happy for any idea! :)

Cheers,
  Marianne

**Comment by silent-303** [comment]
Hey,
if i remember right you need to assign it as a sensor to work as switch.

**Comment by sysadmama** [comment]
I can answer my own question :)

> But it's not possible for me to use it, because I can't assign it to a group: it's still **not** listed under _available switches_ oO

I work with the archives mentioned here: https://phoscon.de/en/raspbee/install
As I figured out, the provided version `2.05.67` was too early as the Aqara magic happened in `2.05.69` - but 67 is the latest `STABLE` they offer.

I switched to `BETA` for today which brought me `2.05.70` on my Pi – and now everything works like a charm <3

Perhaps this helps anyone.

Cheers,
  Marianne
