### ISSUE TITLE
Issue reaching https://dresden-light.appspot.com/discover!

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#1884]
![image](https://user-images.githubusercontent.com/30700296/65217654-f91e6d00-dab4-11e9-860a-cf427ee16c90.png)

Is the site off line, or to popular now?

**Comment by manup** [comment]
The second one :) Albeit the quota was increased several times, it gets hit faster since way more gateways are up.

We are currently switching to a new solution as described in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1595#issuecomment-532987000

**Comment by wvuyk** [comment]
Oh, ok. I am using this same link in my plugin. I better start using it too then. How long before the old link will be removed?

**Comment by manup** [comment]
>I better start using it too then

Yes I'd recommend that. Please note that the new service might have very small down times (a few seconds here and there) while it is developed and until we have our load balancer finished.

Since the traffic already is heavy you might notice some timeouts or errors in the logs. But mostly it should work at least after a few seconds on the next query attempt.

>How long before the old link will be removed?

We're planning to keep it alive for at least one year, maybe more, since there are many gateways which use older versions.

**Comment by wvuyk** [comment]
I will make sure access is allowing a bit of slack, with a few slow retries for now.

Thanks! It might indeed take some time here to for the users to switch over. Not all want to be on the latest....
