### ISSUE TITLE
Websocket does not return brightness in particular case

### ISSUE THREAD

**Issue by androme13** [dresden-elektronik/deconz-rest-plugin#203]
Hi, when a bulb is in a philips hue dimmer group and when the hue dimmer changes brightness with buttons, the new value of brightness is not returned via websocket.

{"e":"changed","id":"1","r":"sensors","state":{"buttonevent":3000,"lastupdated":"2017-09-19T14:42:21"},"t":"event"}
{"e":"changed","id":"1","r":"sensors","state":{"buttonevent":3001,"lastupdated":"2017-09-19T14:42:22"},"t":"event"}
{"e":"changed","id":"1","r":"sensors","state":{"buttonevent":3003,"lastupdated":"2017-09-19T14:42:22"},"t":"event"}
{"e":"changed","id":"1","r":"sensors","state":{"buttonevent":2000,"lastupdated":"2017-09-19T14:42:28"},"t":"event"}
{"e":"changed","id":"1","r":"sensors","state":{"buttonevent":2001,"lastupdated":"2017-09-19T14:42:28"},"t":"event"}
{"e":"changed","id":"1","r":"sensors","state":{"buttonevent":2003,"lastupdated":"2017-09-19T14:42:29"},"t":"event"}
{"config":{"battery":100},"e":"changed","id":"2","r":"sensors","t":"event"}
{"e":"changed","id":"1","r":"lights","state":{"bri":157},"t":"event"}

as we can see the brightness is reported only many seconds after last press on button.

**Comment by ebaauw** [comment]
Actually changes to brightness (and other light state attributes) are reported through the web socket just fine.  The issue you're facing is that the gateway (deCONZ, or any other ZigBee gateway, like the Hue bridge) needs to update it's cache of the light state, before the web socket event is pushed.  This cache is updated through three mechanisms:
1. The gateway tries to guess what the effect to the light state will be of commands it issues to the light.  Normally this works pretty well, except for longer transitiontimes and relative commands (like bri_inc - which is not yet implemented, or the commands send from the dimmer switch to the group);
2. The gateway polls the light states periodically.  The more lights you have, the longer this takes.  The delayed notification you see is the result of the light being polled;
3. The light might send a push notification to the gateway when its state changes.  In ZigBee speak, this is called attribute reporting.  In all their wisdom, Philips decided not to support this in their lights firmware.

So in order to get the notifications you want, either (3) change light bulbs (both Osram and Ikea support attribute reporting, Philips and innr don't) or (1) don't use the group to change the brightness, but use gateway rules instead (this is what the Hue bridge does).

**Comment by androme13** [comment]
Thank you for your reply.
