### ISSUE TITLE
Paulmann LED-Controller

### ISSUE THREAD

**Issue by AntiHeld889** [dresden-elektronik/deconz-rest-plugin#231]
A friend of me soon wants to change also on the Raspbee module, however, we wanted to look first whether his available LED controller also works. But there are no resource(s) in the REST API.

<img width="1277" alt="bildschirmfoto 2017-10-16 um 15 06 04" src="https://user-images.githubusercontent.com/4448275/31614056-498152d0-b285-11e7-85e9-d7491a512257.png">

**Comment by manup** [comment]
Interesting haven't seen these yet :)
Should work in 2.04.83

**Comment by AntiHeld889** [comment]
working

**Comment by beatpaul** [comment]
Hi there! following this conversation and was really happy to get the new version 2.04.83 (84), but my paulmann SmartHome ZigBee Cephei (https://de.paulmann.com/leuchten/smart-home/zigbee/smarthome-zigbee-cephei-schalt-controller-max.-1000w-ac/50043) is still not recognized in the rest plugin.
I
![bildschirmfoto 2017-10-28 um 22 30 03](https://user-images.githubusercontent.com/33185643/32138265-e68454b6-bc2f-11e7-9e28-095c3545534a.png)
Is there a way to fix this ?

thx, Paul

**Comment by manup** [comment]
Should be simple to fix, can you please provide a screenshot from the endpoint–cluster list, as seen in the screenshot above (click on the right circle of the node).

**Comment by beatpaul** [comment]
Thx for the quick answer, here is the screenshot. if u nee any further info let me know!
![bildschirmfoto 2017-10-29 um 18 57 54](https://user-images.githubusercontent.com/33185643/32146668-31ff4710-bcdb-11e7-8f6a-e0fbda24b14a.png)

**Comment by manup** [comment]
Thanks, should work in next version 2.04.85.

**Comment by beatpaul** [comment]
@manup Hi again! I have one more Question: I just realized, that the device i asked to integrate is a switch not the dimmable version, will the dimmable version also work in version 2.04.85  (i'm not e programmer, but i red something like "DEV_ID_Z30_DIMMABLE_PLUGIN_UNIT:" in the code :) ?
I'm thinking of ordering / changing it if this is or would be possibel.
Grezz! and thanx for your support!

**Comment by manup** [comment]
I've added both, so they *should* work but it's not tested yet :)

**Comment by beatpaul** [comment]
Perfect! I just ordered the dimmable device -> i‘ll give u a feedback for both devices as soon as i can test them :)

**Comment by beatpaul** [comment]
@manup: the Paulmann switching device worked flawlessly! (tested with Deconz and Rest Plugin + homebridge) --> thx
As soon as i get and test my dimming device i let u know the result!

**Comment by beatpaul** [comment]
... so luckily the dimmable device was shipped fast and I already installed it ... works perfektly ... so i guess this issue is solved !

thx again for this fast support!

**Comment by beatpaul** [comment]
Hi Manup!

Im really happy with the deconz system and thx again for including the paulmann dimmable device (see this issue)
The problem i have is that just this light switches on randomly some times during day or night. That happend since i installed it, but first i didnt care to much ...
It would be very kind if you could check the code once again

Thx in advance !!
Beatpaul

**Comment by manup** [comment]
Hard to tell what's going on. deCONZ doesn't turn on lights on it's own.

Can you enable logging and provide that log when the light has turned on by its own:

    deCONZ --dbg-aps=1 --dbg-info=1 --dbg-http=80 > log.txt

**Comment by beatpaul** [comment]
Hi @manup !

Here ist the log.  
The Paulmann LED Controller turned on at time

- 20:36 and
- 20:46  
(+/- 1 minute).

Short Log (I deleted some Parts, because of data size > 190 MB):
[https://www.dropbox.com/s/69z2ecbv2kshex8/log%20short.txt?dl=0 
](url)

Full Log:
[https://www.dropbox.com/s/c6fj1rs7zwyvmvi/log.txt?dl=0](url)

Im Using deCONZ in combination with the homebridge-hue (@ebaauw )plugin.

If you need further information let me know.
Thx in Advance fro your help.

Greez Paul

**Comment by beatpaul** [comment]
Hi again!
@manup: any idea about the log?
