### ISSUE TITLE
New Device Support Request - Visonic NEXT PLUS K9-85 SMA

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#2721]
Would you please kindly add support for the above?

![image](https://user-images.githubusercontent.com/52735978/80293908-23e94600-87a7-11ea-848e-dbf4ddfc6967.png)

![image](https://user-images.githubusercontent.com/52735978/80294012-61020800-87a8-11ea-9ae7-bf7cc018cc98.png)

Thank you

**Comment by SwoopX** [comment]
Please provide all relevant screenshots. You may take #2583 as an example. It is also important that the attributes have been read before taking them (its not the case above). Thanks!

**Comment by meremortals70** [comment]
I apologise for not providing all which was required.

Then I read the basic cluster this is what is provided.

![IMG-2349](https://user-images.githubusercontent.com/52735978/80322568-61aea300-8869-11ea-8cb8-bfe240faf292.PNG)
![IMG-2348](https://user-images.githubusercontent.com/52735978/80322573-68d5b100-8869-11ea-9373-83aa2703676d.PNG)

**Comment by SwoopX** [comment]
The device unfortunately does not seem to have paired correctly, as I cannot imagine the shown clusters (just basic) and the device profile (ffff) are correct.

Try physically resetting the device (e.g. there should be a button on the device which must be pressed or certain amount of time) and do a new sensor search again in Phoscon.

Also, when making the screenshots, please ensure the devices are "awake". You can wake them by pushing any physical button on the device repeatedly, wave you hand infront of a motion sensor, move the magnet for a dor sensor, etc.. All the attributes are not populated with usable values right now.

**Comment by meremortals70** [comment]
No difference, I deleted and re-added.

Is it possible that although this is a zigbee device it is not ZHA compliant?

**Comment by SwoopX** [comment]
@ebaauw does that somehow ring a bell how the node is presented? This look like far from being complete. I've seen something similar so far only twice: once with the Xiaomi ZB3.0 smart plug (surprisingly) and accidentially yesterday with one of the Develco smoke sensors.

@meremortals70 Try reading the node descriptor and the simple descriptors once again (can be done via the black bullet right next to the one which is selected in your screenshot).

**Comment by ebaauw** [comment]
> Is it possible that although this is a zigbee device it is not ZHA compliant?

The screenshot shows that the device advertises the ZHA profile on endpoint 0x01, so that's not the case here.

There are plenty of Zigbee devices that use a different profile than ZHA (or ZLL) and consequently aren't supported by deCONZ.  I doubt you'll find many of these in the consumer market though.

>  does that somehow ring a bell how the node is presented? 

Yes, many versions ago, before Manuel improved the discovery.  @meremortals70, what version of deCONZ and RaspBee/ConBee firmware are you running.

It could actually mean two things:
- The device indeed only advertises this endpoint and cluster in the descriptors.  I have no idea what kind of device this is supposed to be, but we've seen some _IAS Zone_ devices that don't advertise all clusters;
- deCONZ hasn't read the descriptors.  Try to read them (select the node, pressing `1` and `8` several times, while keeping the device awake).  You might need to close the network - I've seen some intermittent issue with deCONZ not sending the _Descriptor Request_ message while the network is open.  Where you able to read the _Basic_ cluster attributes?

**Comment by meremortals70** [comment]
deconz v2.05.75
Conbee Firmwave v26490700

The unit is a residential/commercial PIR used by Telstra's Smart Home in Australia.

It is no longer listed on the Visonic website so obviously deprecated.

The replacement zigbee PIR's on the website says zigbee alliance compliant ZHA1.2 and OTA upgradeable.

I will delete/add and try reading again.

**Comment by meremortals70** [comment]
I have retried setting up this sensor with the same result.

I think we can assume and from some googling that it is not ZHA compatible.

The vendor's website lists a new model which is ZHA compatible and I have ordered.

**Comment by SwoopX** [comment]
@meremortals70 Since I'm just playing around, you could try the following with the sensor:

- Physically reset the device
- Start sensor seach in Phoscon
- After like 10 secs, go to deconz GUI and set permit join to 0 (EDIT -> Permit Join)
- Now read the simple descriptors

The result should be that you have to black bullets on the right side of the device (like with the others).
