### ISSUE TITLE
Unable to modify 'duration' parameter in sensor config

### ISSUE THREAD

**Issue by snillevilla** [dresden-elektronik/deconz-rest-plugin#296]
I was really excited to see that the 'duration' parameter for presence sensors has returned in the latest versions of deCONZ REST API! But unfortunately I do seem to be unable to update it via the REST API like I did before. 
When I send a 'PUT' request to [pi-ip-address]:80/api/homeassistant/sensors/[sensor-id]/config with body 
```
{
  "duration": 5
}
```
I get response:
```
[
    {
        "error": {
            "address": "/sensors/1/config/duration",
            "description": "parameter, duration, not available",
            "type": 6
        }
    }
]
```
Which makes me really sad!
Any chance the parameter could become modifiable again?
I COULD be able to achieve the effect I am looking for by sending a PUT request to [pi-ip-address]:80/api/homeassistant/sensors/[sensor-id]/config/ with 
```
{
  "on": false
}
```
the desired amount of seconds after "on" is set to true, but that feels like slightly too much hassle. :(

**Comment by manup** [comment]
Problem seems to be that the duration parameter is derived from the settings from the wheel on the back of the sensor and treated read only. We can add logic, so that values other than the "wheel-values" are allowed too and won't be overwritten by incoming sensor commands. 

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/rest_sensors.cpp#L768
