### ISSUE TITLE
Can't readd Tradfri Dimmer after removing them

### ISSUE THREAD

**Issue by xxLeoxx93** [dresden-elektronik/deconz-rest-plugin#2973]
Hello,

## Issue
two of my Tradfri dimmer dropped the connection over night and didn't respond anymore (a click didn't do anything), so I deleted them both in order to repair them via the delete function in Phoscon web.
Now neither of both can be readded, but they can still be paired to a tradfri gateway.

## Environment
I reverted back from the latest beta to 2.05.77 before the issue happend.
Gateway firmware: 26580700
Device: Conbee 2
Host Rasberry Pi 4

**Comment by xxLeoxx93** [comment]
Update: More dimmer went offline - none of them I could readd anymore...

**Comment by SwoopX** [comment]
Can you share a debug log of the join process with `--dbg-info=2`, please? This might eventually have something to do with a malformed manufacturer name, which should have been catched with .78. That seems to be a bug in the ikea firmware.

**Comment by xxLeoxx93** [comment]
But then I could also just update to .78 to solve it right? I'll try to get the log this weekend.
Is there any chance that the deletion of the swich in phoscon wasn't successfull and now I can't see it there but it's still paired in the bacground?

**Comment by cputoaster** [comment]
seems like I have the same problem, host: ubuntu 20.04 NUC, conbee 2, 2.05.77, but fw 264A0700, did not upgrade yet. No way to add new dimmers atm or make ones with bad batteries work again.

**Comment by cputoaster** [comment]
I switched to 2.05.78 / 26580700 and it seems to work again but needs a few attempts (around 110 nodes)

**Comment by cputoaster** [comment]
I seem to have this this coming up again, or maybe it's a different form. One node dropped off, maybe because of low batteries, but did not come back with new ones. So I tried to deleting it from Phoscon and re-adding it, and after a few attempts stopped trying, but saw this strange node with the name "0x5A9C" and (I think) the MAC address of the dimmer. Any ideas? Can I somehow remove this half-included node?

<img width="1585" alt="Screenshot 2020-07-14 at 09 36 09" src="https://user-images.githubusercontent.com/588059/87397950-76bbe800-c5b5-11ea-8108-ef26f92ac7ad.png">

**Comment by SwoopX** [comment]
Those are incorrectly paired devices. It typically helps if you enter sensor search and read the basic cluster. You currently can't remove them other than directly deleting all remnants in the database (which I wouldn't recommend).
