### ISSUE TITLE
Any chance supporting Salus TRV10RFM?

### ISSUE THREAD

**Issue by markuspf** [dresden-elektronik/deconz-rest-plugin#319]
I am looking at getting these (or, for that matter any) working TRV. Any chance of them getting supported?

**Comment by kylegordon** [comment]
I am also interested in TRV support, such as for the TRV10RFM above, or the eCozy 1TST-EU. There has been some discussion at https://github.com/dresden-elektronik/deconz-rest-plugin/issues/209

**Comment by manup** [comment]
A few weeks ago I've tried to join the TRV10RFM to deCONZ while sniffer was running, after many attempts it did, but then left the network, likely since it waited for some configuration.

So more work needs to be done to inspect what the original gateway UG600 configures, unfortunately I don't have this gateway.

**Comment by kylegordon** [comment]
@markuspf Do you have the Salus UG600 gateway?

**Comment by markuspf** [comment]
@kylegordon no, also I doubt I'd have the time to do any sniffing/debugging. The Gateway itself seems ludicrously expensive (£95 on amazon) as well...

**Comment by mindvisionro** [comment]
Hello, i have the UG600, i want to integrate with home assistant, but for now no results.
If i can help you with some details let me know.

**Comment by bencollins54** [comment]
@manup Any way of making progress with this without the UG600 ?
