### ISSUE TITLE
Philips Hue: Motion detector. Value for temperature and light level is always 0 and will not be updated.

### ISSUE THREAD

**Issue by DenBir** [dresden-elektronik/deconz-rest-plugin#3221]
Hello, I use the  ConBee II USB Stick with deConz in a Debian VM.
App version: 2.05.78
FW version: 26580700

The Philips Hue Motion detector sensor shows always 0 value for temperature and light level and will not be updated.

FW version, motion and battery condition are displayed correctly.

**Comment by Mimiix** [comment]
Hi @DenBir,

My first and only answer would be to check and re-pair the sensor.

Nevertheless: I am closing this issue because you did not stick to a template. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3199

Feel free to open a new issue with the correct template and filled in requirements.
