### ISSUE TITLE
Tuya TS0215 Remote Control (Optical like Heiman HS1RC /HS1RC-M )

### ISSUE THREAD

**Issue by rweise** [dresden-elektronik/deconz-rest-plugin#3251]
The Device will connect with Phoscon but is not shown in Phoscon or IOBroker
I think it is a Heiman HS1RC clone.

Here are the Screenshots with my network settings ...

<img width="849" alt="Bildschirmfoto 2020-09-12 um 09 12 37" src="https://user-images.githubusercontent.com/13751410/92989995-a8c7c880-f4d8-11ea-8f90-cde3d95ae527.png">
<img width="849" alt="Bildschirmfoto 2020-09-12 um 09 12 54" src="https://user-images.githubusercontent.com/13751410/92989996-a9f8f580-f4d8-11ea-9c7a-33b619b9e5b0.png">
<img width="513" alt="Bildschirmfoto 2020-09-12 um 09 14 20" src="https://user-images.githubusercontent.com/13751410/92989997-ab2a2280-f4d8-11ea-8aec-001da4496eb9.png">

**Comment by Smanar** [comment]
Yep, not exactly same cluster but can make a try.

Do you know how to compile code totest, anf have you an Unix machine ?

**Comment by Kenny-59** [comment]
Hello,
I've both remotes:
the tuya/smart9 one whose reference on the package is "Zigbee Smart Remote Controller - Y"
And tje Heiman whose reference is "Zigbee Smart Remote Controller - 2-E"; as you can see on the picture.
Remote are physically the same.

The heiman is correctly associate since the Venus 2_05_81, but Tuya is not.
I've a great hope with the beta Hydaspe 2_05_85 whose some Tuya devices are supported now, but not...
![20201017_155120](https://user-images.githubusercontent.com/73027146/96338889-4478c580-1091-11eb-86ff-b70cd4247057.jpg)
![20201017_155114](https://user-images.githubusercontent.com/73027146/96338891-46428900-1091-11eb-9d7e-c659c83e8247.jpg)
![20201017_155056](https://user-images.githubusercontent.com/73027146/96338892-4773b600-1091-11eb-9734-3b1fdd8b3752.jpg)
Any chance of beeing supported by deconz?

**Comment by Smanar** [comment]
It s possible https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by SwoopX** [comment]
I take care of it

**Comment by SwoopX** [comment]
Added in 2.10.00-beta

**Comment by Kenny-59** [comment]
hi,
nothing new for me with the 2.10.1 and my tuya "Zigbee Smart Remote Controller - Y",
still not supported
regards.
