### ISSUE TITLE
Can’t control Ikea Fyrtur Blinds in deCONZ GUI or Phoscon

### ISSUE THREAD

**Issue by turnyface** [dresden-elektronik/deconz-rest-plugin#3492]
## Describe the question or issue you are having

Running hassio on RPi 3 with deconz add-on.

Stuck on why I can’t control my blinds.

I’ve got everything connected (two blinds, one repeater, and one remote) in the Phoscon app and can see they’re linked in the deconz GUI (but the nodes don’t say anything about blinds). I’ve even got them to show up in the homeassistant app, but nothing I do allows me to control the blinds.

I also am not able to link the remote to the blinds as a switch (nothing shows under available switches) and am only given brightness options for the blinds (linked them in as lights per instructions).

Am I missing something? Do I need to make some edits in configure.yaml to get the blinds to work or do some binding? I’m at a loss

Am I doing something wrong with the linking of devices?

## Screenshots

![53E5D7AD-35B8-4D17-B357-F804B43DB09C](https://user-images.githubusercontent.com/73366707/97055613-c6af3100-154c-11eb-95e7-392da8968542.png)

## Environment

 - Host system: (Raspberry Pi 3)
 - Running method: (Home Assistant deCONZ Add-on)
 - Firmware version: (latest)
 - deCONZ version: (latest)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system: no

## deCONZ Logs
N/A

## Additional context
N/A

**Comment by SwoopX** [comment]
Hi there. As I recall, this is currently not possible. Although this should work in theory, the problem is (simplified) that the blinds are no routers. Withing the groupcasts, special broadcast addresses are available and the one currently used is not suitable for this use case. Apparently, it is not that trivial just to change it. However, we got that on our radar but there's no ETA to be promised.

To stay kinda update on this, you might join our Discord and ask for an update or keep an eye on the release notes.
