### ISSUE TITLE
Slow Sensor Response

### ISSUE THREAD

**Issue by macmanroy** [dresden-elektronik/deconz-rest-plugin#3545]
## Describe the bug

I've been experiencing slow responses from various sensors, noticeably with aqara motion and aqara door sensors. This happens randomly and without pattern, Sometimes i'll open a door or walk into a room and the sensor will report immediately othertimes there is anywhere from a 2 to 5 second delay. I first noticed this with the 0x26370500 firmware update & deconz version 2.05.81
## Environment

    Host system: x86_64 PC
    Running method: Ubuntu Server, Deconz running as hassio addon
    Firmware version: 26390500
    deCONZ version: 2.05.84
    Device: ConBee I
    Do you use an USB extension cable: Yes
    Is there any other USB or serial devices connected to the host system? If so: Yes, a zwave stick

**Comment by Mimiix** [comment]
**On a moderation note, we are missing loads of info. For example logs and additional context. Aslo, host system specs are missing. Please add those, as it may help.**

To answer your question: I had similar behavior on the HA addon sometimes. No clue why, just had it. Since i switched to a native installation of deCONZ on a seperate VM. That solved my issues.

**Comment by macmanroy** [comment]
Having experemeted a bit more it seems that the delay is related to home assistant itself, moving things to node red and bypassing home assistant for automations the delay appears to disappear
