### ISSUE TITLE
Option to name each sensor in a multi sensor device

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#363]
Since not all sensors from multi sensor devices get unique suffixes when created, e.g. _temperature, _light, etc. It would be great if it was possible to name those sensor separate.

I have previously created an issue for Phoscon as well.

https://github.com/dresden-elektronik/phoscon-app-beta/issues/4

**Comment by marthoc** [comment]
Related to this: the Hue Motion sensor has three sensors in the REST API - Light Level, Presence, and Temperature. They all get named the name I give to the main device (eg in my case Living Room Motion Sensor). If I rename the Light Level and Temperature sensors using the REST API (eg to Living Room Light Level and Living Room Temperature), in Phoscon web app the single device is now named “Master Bedroom Light Level”, I’m guessing because lightlevel is the first alphabetically (ie lightlevel, presence, Temperature). 

So +1 for @Kane610’s suggestion - it would be nice to have the sensors displayed separately and renamable separately in Phoscon.
