### ISSUE TITLE
File .elb and deConz a little problem...

### ISSUE THREAD

**Issue by VitoLeo92** [dresden-elektronik/deconz-rest-plugin#380]
I purchased a RaspBee premium module and I want to interface it with an Xbee Pro S2C.

On the Xbee Pro S2C module I have the firmware (router): 23A7.elb.
Now I should load the firmware (coordinator) on RaspBee: 0x21A7.elb.

My question:
Can a firmware be converted from .elb to a .zigbee (or .bin.GCF)? I can do it?

**Comment by manup** [comment]
>Can a firmware be converted from .elb to a .zigbee (or .bin.GCF)? I can do it?

No since the .elb firmware is made for XBee which uses a very different controller than the RaspBee/ConBee.

The XBee S2 can be configured to join the RaspBee network as a router when flashed with a ZigBee firmware, relevant parameters are:

![image](https://user-images.githubusercontent.com/383386/35553012-5fa1ef5c-0596-11e8-9523-10139039a574.png)

**Comment by gmezz23** [comment]
Hello everyone,

sorry for another issue (in real it is the same). This is my advanced settings panel of the router that I intend to set with my deConz

![image](https://user-images.githubusercontent.com/35818395/35933636-76da81ba-0c3b-11e8-8169-cda7c742a80c.png)

what I must set in order to match my raspbee?

![cattura](https://user-images.githubusercontent.com/35818395/35933828-154ba162-0c3c-11e8-84f4-d671040822dd.PNG)

Thank you so much. Sincerly,

Giovanni

**Comment by manup** [comment]
From quick look, set scan channels SC and KY as in the screenshot I've posted above.

You also need to open the network in the WebApp (or search for lights in the Phoscon App).
The XBee should then join the network while search is active.

**Comment by manup** [comment]
And your deCONZ settings is wrong, security must be `High - No Master but TC Link Key`.

**Comment by manup** [comment]
Closing the issue for now since related parameters have been provided.
