### ISSUE TITLE
New Sunricher remotes

### ISSUE THREAD

**Issue by mathos77** [dresden-elektronik/deconz-rest-plugin#391]
Hi @manup, @ebaauw ,

I have received my Sunricher.com devices (remote) today.
They are mains-powered remotes, with in this case, 4 groups and such.
One is CT, whites, the other is color.

http://www.sunricher.com/4-groups-cct-zigbee-touch-remote-controller-sr-zg9002t4-cct-eu.html
and
http://www.sunricher.com/4-groups-rgbw-zigbee-touch-remote-controller-sr-zg9003t4-rgbw-eu.html

Now, I have my Conbee available to sniff anything using Bitcatcher.
Can you guide me through on how we would perhaps get these supported as sensors (with multi-touch eventually) ?

Initially I do not even see them popping up in deCONZ UI. I most probably set some debugging options ?

Kind regards, Tom.

**Comment by mathos77** [comment]
Hmmm, seems I have it paired now:
![image](https://user-images.githubusercontent.com/19706662/35540726-99c65392-0557-11e8-81d1-9817de871625.png)

**Comment by ebaauw** [comment]
I’m not sure these can be supported with buttonevents by the deCONZ REST API, the description indicates it needs to be bound to individual lights, not groups.  deCONZ will have a hard time eavesdropping on the light commands, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/230#issuecomment-359568335.

I’d say first order of business it to bind the switch’s _On/Off_, _Level control_, and _Color control_ clusters of the first endpoint to a light and see that the light can be controlled as group 1.  You should be able to bind up to 12 lights per endpoint.

Next, try binding the second endpoint to a group instead of to an individual light, and see whether the lights in the group respond to the switch.  If that works, sniff what commands the switch sends on each button, I’d expect this to be fairly standard.  Also, we’d need a screenshot of the _Basic_ cluster.

**Comment by mathos77** [comment]
Hi Erik,

The switch can be connected to individual or a group of lights directly, but also to a controller (Which is what I now have done.)

I will make the screenshots, and hook it up to a Hue bulp to see what it does.
Sniffer-wise that is.

Kind regards, Tom.

**Comment by manup** [comment]
The website shows a error (might be a temporarily issue). 

>I’m not sure these can be supported with buttonevents by the deCONZ REST API, the description indicates it needs to be bound to individual lights, not groups. deCONZ will have a hard time eavesdropping on the light commands, see #230 (comment).

Maybe, but if the cluster can be bound to a light it also can be bound to RaspBee/ConBee as unicast binding, same as attribute reporting works.

**Comment by mathos77** [comment]
Here is the Node:
![image](https://user-images.githubusercontent.com/19706662/35557500-98e2a1f8-05a5-11e8-9431-01b2fef71c28.png)


And per item, the cluster Info: (For Color Dimmer Switch, I only have done the 0x01, for the Scene I have a separate 2 screens)

![image](https://user-images.githubusercontent.com/19706662/35557565-c0b51698-05a5-11e8-8b53-1b978040bc4e.png)

![image](https://user-images.githubusercontent.com/19706662/35557573-c5f4e3d6-05a5-11e8-97df-5adaa4a96dc7.png)

![image](https://user-images.githubusercontent.com/19706662/35557593-d1a074b6-05a5-11e8-8566-547ec277c175.png)

![image](https://user-images.githubusercontent.com/19706662/35557601-dacd05cc-05a5-11e8-827d-3e2fdf79edcc.png)

![image](https://user-images.githubusercontent.com/19706662/35557611-e1a2f744-05a5-11e8-8c14-6b15b1c8ef4a.png)

**Comment by ebaauw** [comment]
Could you try and read the attributes in the _Basic_ cluster?  Double-click on each attribute to read them individually if needed.  We need at least the _Manufacturer Name_ and _Model Identifier_.

**Comment by mathos77** [comment]
Hi Erik,
The information is the same for all (4xColorDimmer (0x01-0x04)&& 1xColorScene (0x0A))

![image](https://user-images.githubusercontent.com/19706662/35591265-a4f8cfb2-0609-11e8-8b30-14389e4d9953.png)

![image](https://user-images.githubusercontent.com/19706662/35591308-d0497838-0609-11e8-9240-ab18efb66ac0.png)

**Comment by mathos77** [comment]
@ebaauw Hi Erik,

Do you have tips for me, sniffering the thing ?
If I filter on 0x81F4 I am not seeing that much, so I might need to apply different filters.
I still have to hook it up to a bulb.
Just too much work atm, so little time :(

**Comment by ebaauw** [comment]
Make sure to set the right filter: both source and destination NWK address, with an || (or) - BitCatcher defaults to && (and).  Don't filter on the MAC layer.
![untitled](https://user-images.githubusercontent.com/22179355/35652020-2f62972c-06e2-11e8-9843-aa4c93ba0e16.jpeg)

**Comment by mathos77** [comment]
I see the regular traffic, Routing requests and stuff like that
But when I let's say do anything changing the CT or dimmer or power, I do not see anything in the sniffer (using the filter)

**Comment by ebaauw** [comment]
Does BitCatcher decrypt the packages?  Did you enter your network key?

It migh help to place the ConBee, the RaspBee and the device being monitored physically close to each other.  I prefer to use my test Raspberry with RaspBee for sniffing, with only a few devices connected.

BitCatcher is kind of crude.  I mostly use it for capturing, then export the full log and analyse it in WireShark.

**Comment by s1738berger** [comment]
Any news realting to the wall remotes from sunricher? ( the first remotes I found that look great and intuitive )
I would love to use them with deconz to control ikea and osram bulbs that are already working fine with deconz ( with a RaspBee )
Did you order the remotes as sample direct from sunricher ?

**Comment by alferrari** [comment]
Same question here. Where di you get the devices ? We could share the effort to make them work.

**Comment by velzend** [comment]
Any updates?

**Comment by alferrari** [comment]
It worked for me!

**Comment by velzend** [comment]
Hi @alferrari,

Good to hear it worked for you. What steps did you perform in order to add the wall switches/ buttons to deconz. I like to get events from the web socket. 

I have the 8-fold battery powered wall button switch. It has 4 rows of ON/OFF (1/0).
In order to pair this device I logged-in d the PhosconGW, went directly to switches, clicked new, clicked other in the dialog and clicked next. According to the dialog I have 3 min. to pair the client device.
On the button switch I hold down the left and right button for approx 5 seconds. The blue signal led turns on for about 3 seconds and nothing happens. I tried to manually reset the switch. (by holding the same left and right button till the led turns on and quickly press the left button 5-times, now the led flashes 3 times). 

Any help is appreciated. 

Thanks

**Comment by caplam** [comment]
any news on sunricher remotes ?
I have a ZG2819S-RGBW and i'd like to catch commands in a home automation system.
It exposes 4 home automation color dimmer switch. I guess one for each zone. Each HA has 13 clusters but only basic and power configurations clusters are populated.
As i'm knew to zigbee i''m struggling to learn basics.
I hope to have time to buy a sniffer (any recommendantions for a macos user?) and start gathering useful stuff.

**Comment by rweise** [comment]
Now i own a iCasa remote that is definitely the same, but with other firmware and it works out OTB.
but the Sunricher FW will not work, only Pair 1 and the Master ON/OFF will show a button event :-(

**Comment by Mimiix** [comment]
@rweise Can you open a new device request issue and add the details requested in the template?

**Comment by rweise** [comment]
I will make this tomorrow. By the way, it is also the same Firmware only Manufacturer and Devicename are different and what a bad joke, icasa is not shown in Phoscon , sunricher is - but will not work in IOBroker over deconz.
