### ISSUE TITLE
Send évent to Xbee module via deconz 

### ISSUE THREAD

**Issue by JanmotTimothee** [dresden-elektronik/deconz-rest-plugin#3987]
## Environment

 - Host system: Raspberry Pi 
 - Running method: Home Assistent deCONZ adon 
 - Firmware version: 26
 - deCONZ version: 2
 - Device:  RaspBee II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

## Additional context

Hello, 

I saw your PR about adding xbee to deconz :#2472. 

My setup currently consists of a rasbery pi/raspbee, serving as coordinator. Of ikea plug and aqara sensors . 

I recently bought an arduino and an xbee module. 

Thanks to pr #2472 , I managed to connect to the deconz network. 
I would now like to be able to send events (any) via zigbee. 

Do you think that, in the current state of deconz and without a new zigbee module, it is possible to send an event (home assistant to Arduino) that could be used as a trigger on the arduino ?

Regards

**Comment by ebaauw** [comment]
Technically deCONZ is already sending and receiving messages: it reads the descriptors from the XBee.  The issue is finding a common application-level protocol between deCONZ and the XBee.  There’s two approaches for that:
- Add support for Digi’s Drop-In Networking profile to deCONZ.  This is what the old [XBee plugin](https://github.com/ebaauw/deconz-xbee-plugin) did, but I haven’t really looked at that for a very long time.  Ideally, this support would be exposed over the REST API;
- Add support for the Home Automation profile to the XBee.  Basically, you would have to write a Zigbee application for the XBee, that runs on the Arduino (or on the XBee’s microcontroller if you have a model that includes one), implementing a standard ZHA device.  Start by intercepting the ZDP calls and exposing a ZHA endpoint with a _Basic_ cluster, so the REST API plugin has something to expose.

Both approaches are very doable, and an awful lot of work.
