### ISSUE TITLE
Strange devices appear and cannot be deleted

### ISSUE THREAD

**Issue by clipse2004** [dresden-elektronik/deconz-rest-plugin#4335]
## Describe the question or issue you are having

Hello all, 
I have noticed for a long time that unidentified devices appear again and again. 
Even if I delete them, I have them 10 minutes later again in Deconz. 
No matter what I do I can not identify these devices. 

Can I somehow delete them permanently? Or somehow find out what exactly these devices are supposed to be? 

## Environment

Commercial Version -  2.07.01
Build with Qt 5.11.3
Node limit 200 (max. 200)

2.07.01 / 8.12.2020

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26680700
 - deCONZ version: 2.07.01
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No
![devices](https://user-images.githubusercontent.com/47680803/106649188-8458af80-6591-11eb-89bf-82e9a1cf08c2.JPG)

**Comment by SwoopX** [comment]
Presumably, those are device nearby which are in pairing mode or not connected to any network (if those aren't yours). Currently, you can only permanently delete those inside deconz' DB, where you should exactly knwo what you're doing.

Also, in case those devices should have caught your network configuration due to whatever reason, they will re-appear regardless.

**Comment by clockbrain** [comment]
If you enter the IEEE address (or at least the first say 6 digits) into a MAC lookup service such as [https://www.macvendorlookup.com/search](https://www.macvendorlookup.com/search) you can at least identify the vendor. One of those devices is from TI.
