### ISSUE TITLE
Manufacturer name and model (_TZ3000_rdtixbnu and TS0121)

### ISSUE THREAD

**Issue by fernandodelucca** [dresden-elektronik/deconz-rest-plugin#4523]
## Describe the question or issue you are having

This device of mine appears as that name _TZ3000_rdtixbnu, how do I make the name as friendly as it appears other devices on my network? 
#4457 

## Screenshots

![image](https://user-images.githubusercontent.com/5623038/110165661-02e37f80-7dd2-11eb-83ff-cb568e9dc45e.png)

## Environment

 - Host system: Ubuntu 20.04.2
 - Running method: Virtual Machine
 - Firmware version: 26680700
 - deCONZ version: 2.10.02
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Smanar** [comment]
Hello
_TZ3000_rdtixbnu is not the name, but the manufacture name, the name is "smartplug010" and you can edit it using the "pen" just close the name

**Comment by fernandodelucca** [comment]
Hello Smanar,
Can I change the name of the manufacturer to be friendly like the others? 
![image](https://user-images.githubusercontent.com/5623038/110169988-45a85600-7dd8-11eb-8127-130aa5dab667.png)

**Comment by Smanar** [comment]
Ha, no ^^, it s a long story, but no, for tuya this "no friendly" name is realy important to reconize the device, but all device with this kind of name will be tuya device.

**Comment by fernandodelucca** [comment]
LoL, thanks for your answer, it was clear to me. I didn’t understand why some had friendly names and others didn’t, but I imagine it’s because there are particularities between Router and End Devices

![image](https://user-images.githubusercontent.com/5623038/110171304-49d57300-7dda-11eb-866e-3af8652ae97f.png)

**Comment by Smanar** [comment]
No, it something possible, we can change this name direclty in the api, or keep it in the API but change it before print it, it happen for some tuya device from lidl.
But the problem is tuya device have same model id, so we need the manufacture name to reconize the device, and this is for all tuya device, router and end device.

**Comment by fernandodelucca** [comment]
Really cool, does that make Tuya devices worse than others? just to know if I should keep buying from them.. lol

**Comment by Smanar** [comment]
They are more exotic, there is some of one of them with some issues (not always their fault, it s new stuff), but I have generaly good return from them.
They are exotic because they are using a special cluster, but for me more zigbee compliant than some device using standard cluster.

For me better stuff than xiaomi, less mesh problem. There is som much tuya device, you can find the better like the worse.

Having a friendly name displayed, is something possible, the code will be able to use a product name soon, the application just need to display other thing than the manufacture name.
But not for the moment, and not possible to change it in the API.

**Comment by fernandodelucca** [comment]
perfect the explanation @Smanar, thank you very much!
