### ISSUE TITLE
Is transitiontime expected to work with the "on" parameter?

### ISSUE THREAD

**Issue by deviantintegral** [dresden-elektronik/deconz-rest-plugin#4548]
## Describe the question or issue you are having

I noticed that setting a `transitiontime` when controlling a group only works if I also specify `bri` in the request. If I omit that parameter, the transition time is ignored. I've tested this with both Sengled and Ikea bulbs, so I don't believe this is a device issue.

For example:

```bash
$ curl -X PUT -d '{"on": true, "transitiontime": 50}' http://homeassistant.local:40850/api/REDACTED/groups/5/action
```

If that's the case, are there any other fields that don't respect transition times? Let me know and I can file a PR to update https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/groups/#parameters_4

In the meantime, what I think I can do is set the transition time attribute on each bulb in the deconz UI. I'll try that and report back here.

(somewhat) related: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/149

## Environment

 - deCONZ version: (2.09.03)

**Comment by ebaauw** [comment]
The Zigbee _On_ and _Off_ commands don't take a _Transition Time_ parameter; _Move to Level (with On/Off)_ does.  The latter command is issued when both `on` and `bri` are specified in the PUT request; the first when only `on` is present.

**Comment by deviantintegral** [comment]
Thank you! I've filed an initial pull request, so closing this now.

**Comment by deviantintegral** [comment]
Regarding setting the transition time for each bulb: I was able to set it on my Ikea bulbs, but it appears to have no effect, or at least not with multi-second transition times. The Sengled bulbs I have don't support those attributes at all.

**Comment by ebaauw** [comment]
Transition time is a parameter to some Zigbee commands, not an attribute.  You cannot set it.  The REST API accepts it in the body of a PUT request for a light state, but doesn't report it when GETting the light state.  You need to specify it in the same PUT request with `bri`, `xy`, or `ct`, e.g. PUT `/lights/`_xx_`/state` with a body of `{"bri": 254, "transitiontime": 300}` to transition to full brightness in half a minute (300 deciseconds).

**Comment by deviantintegral** [comment]
Hm, OK, I must be misunderstanding something. What are these attributes in the Deconz UI for? I'm able to set the "On/Off transition" value, though for this particular bulb it doesn't seem to actually change the behaviour (even though I can write a new value):

<img width="616" alt="Screen Shot 2021-03-11 at 9 48 32 AM" src="https://user-images.githubusercontent.com/255023/110805394-09994900-824f-11eb-996c-1c29a36c6ce9.png">

<img width="578" alt="Screen Shot 2021-03-11 at 9 49 58 AM" src="https://user-images.githubusercontent.com/255023/110805579-377e8d80-824f-11eb-94b6-f6b2a9ed3bc8.png">

**Comment by ebaauw** [comment]
OK, that's unrelated to the `transitiontime` as exposed by the REST API.  These attributes are **not** exposed by the REST API (except for _Current Level_ which is exposed as `state.bri`).

These attributes are less common (the Hue lights don't support _OnOff Transition Time_ nor _On Level_ and act as if they're set to 4 and 255 respectively.  I've seen lights that expose these attributes and implement them correctly.  Some cheaper lights might expose, but not correctly implement them.  Note that the GUI is just an graphical user interface to the Zigbee device; the functionality is implemented in the light firmware.

_Remaining Time_ should show the remaining on time when you issue _On with Timed Off_.  _On/Off Transition Time_ should work with plain _On_ and _Off_ commands.  The API only sends these when setting `state.on`, without `state.bri` or `state.transitiontime` (because then it reverts to _Move to Level (with On/Off)_.  Note that the API behaves differently for `/lights` vs `/groups` here.  _On Level_ sets the brightness level on _On_.  255 means: previous value.  _PowerOn Level_ sets the level when the light boots (provided _PowerOn On/Off_ isn't set to _Off_).
