### ISSUE TITLE
Ewelink ZigBee Relais 

### ISSUE THREAD

**Issue by b2un0** [dresden-elektronik/deconz-rest-plugin#4642]
## Device

- Product name: Ewelink ZigBee Relais
- Manufacturer: eWeLink
- Model identifier: currently as ZB-SW01, but looks wrong
- Device type : on/off Plug (Relay)
- Product: https://a.aliexpress.com/_u60ZaN

The Device is currently discovered as Light, instead of Plug

## Screenshots

![image](https://user-images.githubusercontent.com/2155498/112465631-3b3d0480-8d65-11eb-8016-64edbcbdac60.png)

![image](https://user-images.githubusercontent.com/2155498/112465699-4e4fd480-8d65-11eb-9fde-385867ca96e4.png)

### Basic
![image](https://user-images.githubusercontent.com/2155498/112466125-c74f2c00-8d65-11eb-99cf-fd401f5f8588.png)

### On/Off
![image](https://user-images.githubusercontent.com/2155498/112466377-185f2000-8d66-11eb-9820-fce1bc0f598c.png)

**Comment by SwoopX** [comment]
The device should be fully working, or not?

**Comment by b2un0** [comment]
yes, the device is fully working.

**Comment by goermezer** [comment]
The OnTime and OffWaitTime attributes are read only. Is it possible to define them as writable, so that I can change them? In the UI of deCONZ provides the possibility to change them. But the attributes do not change.

I would like to use this device as a door opener, but the inching time with ~0.5s is too short. I would like to set about 3-5 seconds wait time until switching the relay off.
