### ISSUE TITLE
Direct binding

### ISSUE THREAD

**Issue by stigvi** [dresden-elektronik/deconz-rest-plugin#4664]
## Describe the question or issue you are having
Hi. I consider myself an experienced user. I have a zigbee network with 150 nodes and a lot of Hue Dimmers which are binded directly to light groups. I like the extra safety it gives me being able to control light even if Home Assistant is not running. Setting up the binding in the bind dropbox was easy enough when done some time (a year) ago. But now I have two more dimmers to set up and it is impossible for me to get this to work. The bind process is confirmed with a success message, but nothing works. I have double and triple checked the group number and also confirmed that the light is in this group. I have also tried an old group where an existing dimmer is binded and working, but I can not get the two new ones working. All dimmers are on the same firmware version.

Can someone confirm that the bind dropbox is working in version 2.10.4? And does someone know of an obvious setting I could have missed?

## Screenshots
![image](https://user-images.githubusercontent.com/25978315/112761361-3ee9b900-8ffb-11eb-81c4-1e6200f70105.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26680700)
 - deCONZ version: (2.10.04)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? APC UPS

**Comment by ebaauw** [comment]
Normally the REST API plugin creates a group and sets up the binding when you pair the switch.  You can find out the group, by checking `config.group` on the `/sensors` resource.  I don't know how many bindings the switch supports, but you might need to delete the old binding, before binding to the new cluster.

I think this is the "old" model Hue dimmer (with two endpoints)?  Looks like the right binding to me.  Are you trying the _On_ of _Off_ button?  For _DimUp_ and _DimDown_ you might need to bind the _Level Control_ cluster as well.

If it supports multiple bindings (per cluster), you would get websocket notifications (when pressing a button) of `config.group` changing between the group bound by the API vs the group manually bound by you.  If `config.group` doesn't change (when pressing a button) to the group you bound, the sensor isn't acting on the new binding.

**Comment by stigvi** [comment]
>I think this is the "old" model Hue dimmer (with two endpoints)? Looks like the right binding to me. Are you trying the On of Off button? For DimUp and DimDown you might need to bind the Level Control cluster as well.

Yes, this is the old Hue dimmer and it is new out of the box. Currently, I have only tried to get the on/off cluster to work.
After I have added the binding to the switch, I am able to remove this binding and it is confirmed with a success message in the bind dropbox shown in the first post. If I try to unbind a second time, it says that the binding does not exist and as expected. So it seems the binding is stored in the switch, but it is not possible to turn the light on/off.
I have also checked that the light (they are Philips Hue) are in the correct group by query for group information in deconz.

**Comment by Smanar** [comment]
Someone remember the Zigbee Group limitation (if there are) ? Like the maximum device in a group, the maximum group for the same light, the maximum remote in a group, ...

**Comment by ebaauw** [comment]
There is no limit to the number of lights in a group (other than the number of devices in a network).  Remember that, in Zigbee, you add a group to a light, not the other way round.  Group membership is stored on the light.  The number of groups that a light supports depends on the light firmware.  I've seen anything from 8 to 80, I think.  Same for scenes.

Also, there's no limit to the number of remotes that can be bound to the same group; the binding is stored on the remote.

**Comment by rpsainio** [comment]
Well, the answer is yes and no: The binding box works in general, however it seems to me that you are better off using phoscon for configuring the dimmers. The reason is that now days they use indirect binding == the switch is bound to a dummy group the deconz listens to and then will send the command to another group (normally where the lights belong to). This way they can quite easily change the functionality. Took me awhile and zshark/wireshark to figure this out. 
Besides, if you bind the switch to the group lights belong to then the entry in phoscon UI will suddenly disapppear..

**Comment by stigvi** [comment]
I suppose you mean like this? 
![image](https://user-images.githubusercontent.com/25978315/115892350-5b8cdb80-a457-11eb-81c5-d7531e6bdfa1.png)

But doesn't this require deconz running to turn light on / off? One reason for making direct bindings was to be able to turn on light even if my home automation being down.

**Comment by rpsainio** [comment]
Right, with "indirect" binding above mentioned mapping is easy as it happens in deCONZ. Well, I think you need now  days deCONZ running so that this mapping works. I have used deCONZ for some years already and I was sort of surprised see this after I just upgraded to latest and greatest. OTOH my raspi runs behind a UPS and within last years I cannot recall deCONZ stopping unless I wanted to.
As I said, the binding box still works and I think you can do direct bindings also, however you cannot use those devices in  phoscon any longer. Right now I have a mixture of direct-bindings and indirects. OTOH, for emergencies it is possible to have a switch broadcasting to all, so the lights can be switched on. OSRAM Lightify switches have this by default when initialized.

**Comment by xxLeoxx93** [comment]
@rpsainio 
Did you follow any guide on how to make those bindings? I'm trying to bild a remote to three ikea fyrtur blinds but noi luck so far...

**Comment by ottelo9** [comment]
same here, bind dropbox doesnt work for me.
@ebaauw could you help us?

**Comment by Mimiix** [comment]
@ottelo9  I think it would be more usefull to post on the forums or join discord :)
