### ISSUE TITLE
Telekom Contact Sensor support

### ISSUE THREAD

**Issue by RobusK** [dresden-elektronik/deconz-rest-plugin#47]
Hi,

I'm trying to get one of these to work and be visible in the REST endpoint:
https://www.amazon.de/gp/product/B01JJJ52JQ/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

What needs to be done? I can see the device in deCONZ GUI as such, but nothing in the REST. I've tried fiddling with the zcl files, but with no success

![image](https://cloud.githubusercontent.com/assets/6713161/26530641/04aee11a-43d9-11e7-884f-f6cc275eb913.png)

**Comment by manup** [comment]
Hi, can you please provide:

* model id from basic cluster (cluster info)
* manufacturer code (node info)

I'll add them to the supported devices list, the sensor should be visible via REST API after rejoin while sensor search is active.

In the related commit you will see how its done.

**Comment by RobusK** [comment]
Hi,

![image](https://cloud.githubusercontent.com/assets/6713161/26530737/0d0ac200-43db-11e7-8dae-095a4301faff.png)
![image](https://cloud.githubusercontent.com/assets/6713161/26530761/66ca367c-43db-11e7-9711-45c57e13c3f3.png)

Perfect, thanks!

**Comment by manup** [comment]
Took a while, large commit ahead ;)

https://github.com/dresden-elektronik/deconz-rest-plugin/commit/9a0e2353f32099b8a901e2a675348fc56e53c8ea

Since the Bitron sensor is just a rebranded Climax sensor it should just work with the existing IAS Zone code.
In order to test it, please start sensor search and reset the sensor as described in the manual (often button press for 10 s). After rejoin the sensor should be discovered as presence sensor in the REST API and also trigger realtime events via web socket.

*Note:* Beside the REST API call you can start sensor search in the Web App > Settings > `Open network`

**Comment by RobusK** [comment]
Hi @manup ,

I just pulled & compiled from master - sadly the sensor still doesn't show up at /api/foo/sensors :(

`{
  "1": {
    "config": {
      "battery": 100,
      "on": true,
      "reachable": true
    },
    "ep": 2,
    "etag": "39b91dcb6242bbd89987c495e8725126",
    "manufacturername": "Philips",
    "modelid": "SML001",
    "name": "ZHALight 1",
    "state": {
      "lastupdated": "2017-06-05T22:57:06",
      "lightlevel": 7827
    },
    "swversion": "6.1.0.18912",
    "type": "ZHALight",
    "uniqueid": "00:17:88:01:02:03:af:3d-02-0400"
  },
  "2": {
    "config": {
      "battery": 100,
      "on": true,
      "reachable": true
    },
    "ep": 2,
    "etag": "39b91dcb6242bbd89987c495e8725126",
    "manufacturername": "Philips",
    "modelid": "SML001",
    "name": "ZHAPresence 2",
    "state": {
      "lastupdated": "2017-06-05T22:57:18",
      "presence": false
    },
    "swversion": "6.1.0.18912",
    "type": "ZHAPresence",
    "uniqueid": "00:17:88:01:02:03:af:3d-02-0406"
  }
}`

**Comment by manup** [comment]
Needs to be rechecked, the sensor is in the whitelist.

Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
