### ISSUE TITLE
Cannot open Deconz app via VNC

### ISSUE THREAD

**Issue by hesspoint** [dresden-elektronik/deconz-rest-plugin#4839]
## Describe the question or issue you are having

Hi,
I have the issue that I have a Pi with a Raspbee II and the Pi is headless.

I can connect to the Pi via SSH and also via VNC on my iPad Pro (also tried on my MacBook). I can start Deconz on the command line and I can access the Phoscon app, add devices etc. everything fine.

However I want to open the Deconz app to be able to see the signal strength of the devices.

So I connect to VNC  and then open Programming > Deconz. And nothing happens. I thought the app is broken but when I connect the Pi to a screen and keyboard then I can open the Deconz app without any problem. But not in VNC. That is super strange.

Also I cannot use that way because I need to move the Pi to a different room and I need to to see the signal strength from the location where it is normally located. So VNC is the only option.

## Environment
Raspbee II on Raspberry Pi 4b
I think all latest firmware

I am running “Deconz” not Deconz-GUI.

I enabled auto start via
$ sudo systemctl enable deconz
$ sudo systemctl start deconz

I also tried stopping Deconz and starting Deconz-GUI but that also does not work.

## deCONZ Logs

$ **sudo service deconz status**
● deconz.service - deCONZ: ZigBee gateway -- REST API
   Loaded: loaded (/lib/systemd/system/deconz.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-05-05 20:49:39 CEST; 57min ago
 Main PID: 19098 (deCONZ)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/deconz.service
           └─19098 /usr/bin/deCONZ -platform minimal --http-port=80

May 05 20:49:39 Raspbi systemd[1]: Started deCONZ: ZigBee gateway -- REST API.
May 05 20:49:39 Raspbi deCONZ[19098]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pi'
May 05 20:49:39 Raspbi deCONZ[19098]: libpng warning: iCCP: known incorrect sRGB profile
May 05 20:49:39 Raspbi deCONZ[19098]: This plugin does not support propagateSizeHints()
May 05 20:49:39 Raspbi deCONZ[19098]: This plugin does not support propagateSizeHints()
May 05 20:49:42 Raspbi deCONZ[19098]: This plugin does not support propagateSizeHints()

$ **sudo service deconz-gui status**
● deconz-gui.service - deCONZ: ZigBee gateway -- GUI/REST API
   Loaded: loaded (/lib/systemd/system/deconz-gui.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2021-05-05 21:49:29 CEST; 14s ago
  Process: 23672 ExecStart=/usr/bin/deCONZ --http-port=80 (code=exited, status=1/FAILURE)
 Main PID: 23672 (code=exited, status=1/FAILURE)

**Comment by senilio** [comment]
This is likely due to your DISPLAY environment variable being different when connected via VNC and via keyboard+monitor.

You can check what DISPLAY the deconz-gui service tries to start up on (likely ":0")
```
sudo systemctl cat deconz-gui
```

Next check what this var is set to in your VNC session, by opening a terminal and go:
```
echo $DISPLAY
```

Your systemctl service file needs to correspond to this. 

As an example, let's say your DISPLAY var within your VNC session is ":1.0"...

1. Create an override file for the deconz-gui service by running `sudo systemctl edit deconz-gui`. Put the following content in the editor, then save the file.
```
[Service]
Environment="DISPLAY=:1"          # use the display number from the first step
```
2. Update the systemd service by running `sudo systemctl daemon-reload`
3. Now try starting the deCONZ via the desktop shortcut, or by running `sudo systemctl start deconz-gui`.

**Comment by zedc92** [comment]
I had exactly the exact same issue. The solution works perfectly. Thansk @senilio

**Comment by hesspoint** [comment]
Awesome thanks so much. That did the trick! You made my day!
