### ISSUE TITLE
Eurotronic Spirit - deCONZ Cluster Info show's also some xiaomi id lines

### ISSUE THREAD

**Issue by gidig** [dresden-elektronik/deconz-rest-plugin#4860]
Everything works fine so far but when browsing/read the basic cluster information of my two Eurotronic Spirit thermostats, 3 IDs were also displayed, which allegedly come from Xiaomi.

There are several Aqara multisensors in the same mesh, which work without problems.

Is that only for me that way?
If not, what can I do with it?
How does this link come about?

## Screenshots

  ![image](https://user-images.githubusercontent.com/29579293/117657052-66ef3f00-b199-11eb-80b5-c49e29f647d9.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26390500
 - deCONZ version: 2.10.04 / 14.3.2021
 - Device: RaspBee I
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

**Comment by SwoopX** [comment]
Currently, additional (manufacturer specific) attributes are exposed by deCONZ core based on the device manufacturer code. Coincidentally, the Spirit and many (older) Xiaomi devices share it. And no, since they're for Xiaomi, they will not work.

It doesn't cause any harm other than scratching heads 😉
