### ISSUE TITLE
Raspbian jessie latest released version is 2.06

### ISSUE THREAD

**Issue by mat1990dj** [dresden-elektronik/deconz-rest-plugin#4907]
## Describe the question or issue you are having
Latest reported version for raspbian jessie is 2.06. Installing other version from http://deconz.dresden-elektronik.de/raspbian/stable/ results in stretch version package deployment and doesn't work.

After
sudo apt update
sudo apt install deconz
Says already at latest version.

From web phoscon web interface also says latest version

## Screenshots
![image](https://user-images.githubusercontent.com/5220059/119250588-62ffeb80-bba1-11eb-9211-f73fc606cec7.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian Jessie
 - Firmware version: 26390500
 - deCONZ version: (2.06.00)
 - Device: RaspBee I

**Comment by manup** [comment]
Sorry we need to update the documentation. Jessy versions are no longer build since Jessie is EOL since June 2020 and we are now using newer compiler features not available in that version.

https://wiki.debian.org/LTS

Highly recommend to update to at least Stretch or better Buster also to get the operating system updated with security patches.
