### ISSUE TITLE
Salcar Zigbee Thermostat (Tuya TS0601)

### ISSUE THREAD

**Issue by laurius** [dresden-elektronik/deconz-rest-plugin#5400]
Device Request for Salcar Thermostat
Product name: Zigbee Smart Thermostatic Radiator Valve
Manufacturer:  _TZE200_a4bpgplm
Model identifier: TS0601

![image](https://user-images.githubusercontent.com/35629808/138147956-14aaf21d-e013-442c-981b-29e8218b33fa.png)

![image](https://user-images.githubusercontent.com/35629808/138147998-8e6ef048-9b60-4ede-ad15-0e7f586ac831.png)

![image](https://user-images.githubusercontent.com/35629808/138148080-94e43225-e6d5-4a36-a52a-26a5d858261b.png)

**Comment by chr997** [comment]
Hi, new here. If anyone can tell me what is missing, I can try to help.
I have this very item, a SALCAR thermostat and it isn't recognized.... can't work with it in FHEM, using deconz

**Comment by Smanar** [comment]
I think all information are here, no need more capture, I think the problem was more the "presentation"

Perhaps someone will re-open this issue ?
Else can make a new one, with sme capture but respecting the presentation rule.

BTW we are ATM trying to make tuya TRV working with DDF, if we can make it working, will be easy to add your device.
Can follow the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5831

**Comment by laurius** [comment]
There is another issue with more information here, let me know if anything is missing:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5401
Sorry i made 2 issues, this was my first one here so didn't know about the structure it should be posted in.

**Comment by Smanar** [comment]
Ha nope, the previous (the https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5401)  was closed by bot, you can re open it yourself ^^
