### ISSUE TITLE
SSL with Proxy not working

### ISSUE THREAD

**Issue by scobby** [dresden-elektronik/deconz-rest-plugin#5509]
## Describe the bug
if i use a SSL Certificate or a authentication middleware infront of deconz i get the wrong ip/hostname from the auto discovery function.

The deconz instance is discovered and displayed in the webpage. But it says "ip: 10.0.03". clicking on that instance doesnt work, because he wants to get https://10.0.0.3:8090/api/ which is wrong, because i opened the webpage with https://deconz.mydomain.com

The local application Storage in the Webbrowser (Screenshot), says the system is 10.0.0.3, but its deconz.mydomain.com.
When i edit the Storage to deconz.mydomain.com everything works perfect....

## Steps to reproduce the behavior
1. Install deconz
2. Setup traefik with ssl and a host-rule
3. Access deconz via dns and https.  -> https://deconz.mydomain.com 

## Expected behavior
Phoscon GUI  with lights and configuration is visible

## Screenshots

![Screenshot at Nov 23 16-47-43](https://user-images.githubusercontent.com/9264361/143057902-f4e53364-9590-475e-8dcb-cc6b543436df.png)

## Environment
 - Host system: (Raspberry Pi )
 - Running method: (deconzcommunity/deconz)
 - Firmware version: (not a firmware bug)
 - deCONZ version: (2.13.02 / 10.11.2021)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?
 - - yes but irrelevant

## deCONZ Logs
no deconz logs, because its a frontend / routing / discovery problem.

**Comment by jngrb** [comment]
I would like to ask for support to use a reverse proxy and a subfolder in the external / public URL, i.e.
https://subdomain.mydomain.com/deconz

The reverse proxy would resolve https://subdomain.mydomain.com/deconz/pwa to http://<IP>:8080/pwa and https://subdomain.mydomain.com/deconz/api to http://<IP>:8080/api (rest) and http://<IP>:8081/api (websocket). This assumes that I start deCONZ with 8080 as rest port and 8081 as websocket port.

I currently cannot hack such a subfolder external URL into the browser's Local Storage settings, because there is no way to inform the Phoscon Web App about the infix between domain and endpoint.
