### ISSUE TITLE
How to complete setup steps without smart lights?

### ISSUE THREAD

**Issue by avraham** [dresden-elektronik/deconz-rest-plugin#551]
Hi,

I'm trying to setup my conbee with this http://www.dresden-elektronik.de/pwa to be able to use it with Home Assistant. I believe I should get an API key once I complete the configuration.

The problem is I don't own smart lights, only xiamoi door sensors. So I'm stuck on the second screen where I'm supposed to turn on my lights. 

How can I get the API key to use conbee with Home Assistant?

**Comment by manup** [comment]
Fear not: this will fixed soon in the Phoscon App.
Until then you can use following workaround:

instead of `/pwa/commissioning.html`
open `/pwa/index.html`

Then create a dummy group and add your sensors in *Menu > Devices > Sensors > Add sensor > Other*.

Note: with recent versions you may also use the local version `http://<raspberry-ip>/pwa`

**Comment by avraham** [comment]
Thank you, that worked :)

**Comment by manup** [comment]
The setup page now contains a short cut link to skip this step.
