### ISSUE TITLE
Disabled certificate verification on curl in deconz-rest-plugin/linux/deCONZ/usr/bin/deCONZ-homebridge-install.sh

### ISSUE THREAD

**Issue by MaxCere** [dresden-elektronik/deconz-rest-plugin#5598]
## Describe the bug

On file deconz-rest-plugin/linux/deCONZ/usr/bin/deCONZ-homebridge-install.sh it's used curl with flag -k in line:
229: curl --head --connect-timeout 20 -k https://www.phoscon.de &> /dev/null
368: curl --head --connect-timeout 20 -k https://www.npmjs.com/ &> /dev/null

The curl help stated about -k flags:
-k, --insecure Allow insecure server connections when using SSL

This can be exploited for a man in the middle attacks.

Just remove the -k flags should solve this low impact security risk.

## Environment

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by ehuggett** [comment]
(FYI I am not associated with this project)

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/8204f08632d42e22905a77e111acc552b7770f25/linux/deCONZ/usr/bin/deCONZ-homebridge-install.sh#L229

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/8204f08632d42e22905a77e111acc552b7770f25/linux/deCONZ/usr/bin/deCONZ-homebridge-install.sh#L368

The only information used from curl command (and theoretically under attacker control) here appears to be is its exit status. 

Given
- no sensitive information is sent by the client (no special headers, get or post)
- all information returned by the server is discarded (`&> /dev/null`)
- this being correct or incorrect would seem to depend upon exactly what it is that should be to tested. Without certificate verification this use of curl seems somewhat equivalent to ping, except it also confirms the host has a HTTPS service running
- Being able to force connectivity checks to pass when they should fail does not seem concerning

The only thing I would do differently here is to use `--insecure` instead of `-k` to disable certificate verification to make it more explicit (it would be an issue if the line was mistakenly reused for something important), maybe a short comment to justify the deviation from best practices.
