### ISSUE TITLE
_TZ3000_4upl1fcj

### ISSUE THREAD

**Issue by Spirit1240** [dresden-elektronik/deconz-rest-plugin#5786]
## Device

- Product name: Scene Switch
- Manufacturer: _TZ3000_4upl1fcj
- Model identifier: TS0041
- Device type : Switch

### Basic

![basic](https://user-images.githubusercontent.com/98969857/153730806-a9f0682d-aad3-43b3-9b7c-e158781744dc.jpg)

### Identify

![phoscon](https://user-images.githubusercontent.com/98969857/153754856-396c3d3f-4f35-4f37-99c4-50cb457ddbc9.jpg)

### On/Off
![on_off_01](https://user-images.githubusercontent.com/98969857/153755087-2af197ba-1cc4-43cd-8eda-b57af4bafea8.jpg)
![on_off_02](https://user-images.githubusercontent.com/98969857/153755094-34e1fd09-992a-4a5a-a9c2-8e1babd7ad81.jpg)

### Node info

![node_info](https://user-images.githubusercontent.com/98969857/153730877-58fd3773-6e75-425d-af96-fba8fd92463b.jpg)

### Power

![power](https://user-images.githubusercontent.com/98969857/153754880-0eb433ce-155c-49d9-a722-ffc232097d99.jpg)

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by hastime** [comment]
@Mimiix - which screenshots do you need I will be happy to add them as I have one of these, I was trying to create a DDF for it, I have it showing up in Phoscon with the DDF now but I can't see any button events and in Phoscon I cannot add it to a group.

Thanks,

Kind regards

**Comment by Mimiix** [comment]
Screenshots seem to be fine, but not all are read so values are missing. 

We want them to be on the opening post though so @Spirit1240 needs to add them.

**Comment by hastime** [comment]
@Mimiix - No problem, I don't want to create a duplicate Device Request, can I ask here, the switch shows in Phoscon and deconz but I get no events in the API or on HA, I also cannot add it to any Phoscon groups, is this because the switch needs whitelisting? 

Also the switch light flashes every now again, is this because deconz is polling it for some reason? The four button version of this switch doesn't flash without user interaction.

Thanks again,

Kind regards.

**Comment by hastime** [comment]
Hi, 

Sorry to keep chasing but is there anything I can do to try and progress this? Or do I need to wait until it goes stale and log a new device request? 

Kind regards

**Comment by Mimiix** [comment]
@hastime feel free to duplicate this one and I'll close this one. Please note that even if your request is valid, implementation can be halted due to #5733. I don't know if this can be done with ddfs.

**Comment by hastime** [comment]
> @hastime feel free to duplicate this one and I'll close this one. Please note that even if your request is valid, implementation can be halted due to #5733. I don't know if this can be done with ddfs. 

@Mimiix Thanks for this I will create a device request for this switch. I understand that due to #5733 it may not progress as fast. 

I think it's worth the delay to have the work on DDFs progressed, because as a user being able to set up your own devices would be awesome! 

As always, thanks for your help!

Kind regards,

**Comment by Mimiix** [comment]
You are most welcome :)

Feel free to ping me in the new request.

**Comment by Mimiix** [comment]
Closing as we have a new , complete issue.

**Comment by MBj1703** [comment]
Sorry for stupid question, but what happened to this request?
I have the same.
