### ISSUE TITLE
Tuya Thermostat TRV TS0601 / TZE200_ckud7u2l battery state not reported

### ISSUE THREAD

**Issue by btk999** [dresden-elektronik/deconz-rest-plugin#6643]
## Describe the bug
The Device TRV TS0601 / TZE200_ckud7u2l is supported by deconz and working fine for me with Homebridge and Apple Home App. But the battery state **config/battery** is not exposed by deconz, instead i just get **state/lowbattery** = true if the battery is empty.
But for most 3rd party apps a percentage battery level is needed. 
Maybe it can be solved with a simple DDF for config/battery like if (State.lowbattery == true) { Item.val = 0 } else { Item.val = 100 } but i could not get that work by myself.

## Screenshots
![image](https://user-images.githubusercontent.com/20415739/210551400-9722a849-c8ae-403c-b4cf-0784f7419cec.png)

## Environment
deconz 2.19.03 / 19.9.2022
fw 26580700
Windows Server 2022 Standard
conbee II with usb extension cable
no other serial devices

**Comment by Smanar** [comment]
From my memory it's because the device itself.
I have check the z2m code and it seem they are doing same, there is a e.battery_low(), but nothing about battery level.

**Comment by btk999** [comment]
Yeah, seems that the device does not support it, but wouldnt it be possible to emulate it in a way i supposed?

**Comment by Smanar** [comment]
Not officially because we will have user that thing the battery return was not accurate ^^ (there is already for batteries sensor).
And not on your personnal side for the moment, but yes In the future will be possible just with adding a line like yours.

For tuya device, the device need to be handled by DDF core or Legacy core, not possible to mix them, and the DDF core is not able yet to manage Tuya TRV device.
It's wip, there is already a code as proof of concept, but PR are locked for the moment.
