### ISSUE TITLE
Add LIDL SilverCrest Plug with Energy Counter

### ISSUE THREAD

**Issue by kabieror** [dresden-elektronik/deconz-rest-plugin#6995]
## Device

- Product name: SilverCrest Plug
- Manufacturer: _TZ3000_j1v25l17
- Model identifier: TS011F
- Device type : Please remove all unrelated device types. 
  - Plug with energy counter

The device is already supported for switching, but the energy measurement is not available in the REST interface.

### Basic
<img width="942" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/9639c6f9-49bd-4a33-9cd8-1168cd3ae7d6">

### Identify
<img width="543" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/ed8ee81d-1d3f-4e5b-8c7f-ea0cd23f8297">

### Groups
<img width="527" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/ec9695dd-cc2d-4d1f-957a-55757f0bdc3b">
<img width="532" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/109deaf2-c0d5-4444-a3e4-7aa51cc26704">

### Scenes
<img width="526" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/05ecc3a8-6f30-4575-900a-b59638fa8b16">

### On/Off
<img width="529" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/d6eb9d0a-faa4-43a6-a163-a1dc331a160a">

### Simple Metering
<img width="543" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/117bd503-63aa-4ac0-87ee-eb4129612dcd">

### Electrical Measurement
<img width="904" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/1dc9b0e8-9bdf-4228-894c-1ec9dd5066be">

**Comment by BabaIsYou** [comment]
Can you try this DDF ? (see https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet for help)

{
  "schema": "devcap1.schema.json",
  "manufacturername": " _TZ3000_j1v25l17",
  "modelid": "TS011F", 
  "product": "LIDL SilverCrest Plug",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0B04"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 300
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 300
        },
        {
          "name": "state/voltage",
          "refresh.interval": 300
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0702"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "read": {"at": "0x0000", "cl": "0x0702", "ep": 0, "fn": "zcl" },
          "parse": {"at": "0x0000", "cl": "0x0702", "ep": 0, "eval": "Item.val = Attr.val * 10"},
          "refresh.interval": 300
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 1,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}

**Comment by kabieror** [comment]
Thanks for the DDF! I tried placing it at /usr/share/deCONZ/devices, restarted the container and re-paired the plug. But there are no new endpoints in the REST API. I also tried setting DDF mode to "hybrid" which did not change anything. Have I missed anything?

**Comment by BabaIsYou** [comment]
AFAIK DDF file won't resist at a container restart doing it that way. May be could try some hnts here : https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839 ... or just update Deconz after merge of the PR.

**Comment by kabieror** [comment]
Actually it does, until you recreate the container or in case of docker-compose, you run 'down' and 'up' again. Okay I'll try again after the upgrade. Tank you!

**Comment by BabaIsYou** [comment]
Better to put it under subfolder`lidl` to have `swversion` correctly parsed. 

Have you tried to load the DDF using DDF editor to see if it kids without error ?

**Comment by kabieror** [comment]
Ah sorry, I forgot to mention this. I tried to load the json in die DDF editor via File>Open... Nothing happens, but the footer shows an error message. The log does not contain any helpful information.
<img width="367" alt="grafik" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/16592633/bfe730f3-a5f5-4172-bbf7-d17a2142466d">

**Comment by kabieror** [comment]
Okay my bad. The file seems to have been copied with errors. Now on the second attempt, it worked like a charme. The REST API now has sensor endpoints showing the current power consumption. Thank you for the fast solution!

**Comment by Pinky007** [comment]
Hej @BabaIsYou ,
I have the same product but seems that I still don't get the measurement.
I saw https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7013 which seems to be merged on v2.22.1 beta.
I am running v2.22.2 as addon in HA, so I would have expect it to be included
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/e7df9269-cbf6-456f-9e03-b8c2133b1006)

Device has been added under lights in Phoscon
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/d74f0757-ff96-46d8-abc6-4d142d3d2484)

But just offer the switch in HA
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/b7896558-e142-4372-8645-294e4689faab)

I tried to check the different cluster info but outside of minor difference that I don't think it make a big change, I couldn't see why it wouldn't work

Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/9b465c4e-972f-406a-a7e0-2f21d025d3e8)

identify
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/f579adc0-ce35-4162-bbca-896a5a5a914e)

groups
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/ce515466-0039-4f7f-9047-a81bc235cf14)

scenes
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/1c1c56de-eeba-438a-bbe1-96dceec83e00)

on/off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/8abdcfc9-4324-44f5-b8bd-5f34297676be)

simple metering
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/c82c138f-dc55-4ab6-a478-66c18fd489b7)

Tuya specific
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/9d4deb8a-4418-40df-a9d3-8e5fbaf445f0)

There is some small DDF differences with yours posted in this thread (marked in red):
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/ada7ee1b-a0ec-48d7-8d76-767f4f502a0c)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/39ec9539-3098-4dbf-9b31-29df87c04a07)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/b10a1ad4-cc5e-4006-b66d-995b1559cb3c)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/5d67db05-dfa8-4e14-b607-af9f2ae0dac5)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/608f1ffe-a207-4076-9a34-8bc921ce5607)

I also let the plug run sometime so that the values where not 0 and where moving (to avoid missing report on only changed value) but this didn't helped.

Let me know if you have any pointer of where this could be coming from or if further data is needed to adapt the integration.

Thanks!

**Comment by BabaIsYou** [comment]
The DDF is in « Silver » state … did you change your deconz configuration accordingly ?

**Comment by Pinky007** [comment]
That was it, thank you for the Hint.
I saw that it was silver in the DDF:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1488257/73434721-93f6-4404-a53b-cf63ff2fd9a9)

But didn't know about enabling the different levels activation mentioned in your link.

Is there a way to bump the integration to gold? Can I help with this?

Thank you for the quick help!
