### ISSUE TITLE
Adding support for  _TZ3000_zl1kmjqx

### ISSUE THREAD

**Issue by SimoBa80** [dresden-elektronik/deconz-rest-plugin#7666]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Temperaure & Humidity Sensor

### Manufacturer

TUYA

### Model identifier

RSH-HS06

### Device type to add

Sensor

### Node info

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/163328007/2316a25c-5ef4-44ba-adf2-f7f434849a24)

### Endpoints and clusters

-

### Basic

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/163328007/28e23acc-eeee-4dcf-aadc-9e56bd1e4e36)

**Comment by Smanar** [comment]
Hello this device work like classic device, it just need the tuya unclock sequence, so you can mimic this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/ih-k009_temp_hum_sensor.json
 and add the tuya unlock sequence.

But the problem is this device don't have model id ? On your first capture, the attribute 0x0005, this one is empty, it's a bug, or this device don't have it ?
If this device don't have it, it will be not possible tu support it.

**Comment by SimoBa80** [comment]
Hi, I bought 2 sensors and one of them has the ID and the other does not:
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/163328007/458a6b5f-8cc4-46f7-b35b-7db560421d7f)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/163328007/dd9d2569-cfee-49ad-a773-53017a797c31)

**Comment by Smanar** [comment]
Nope, the missing information is "Model identifier", to reconise device deconz use it and the "Manufacturer", on the 2 capture you have "unknow".
This is something normal on battery device, because they are sleeper, you need to awake them in same time you ask for attribute"

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

The usefull one are in cluster 0x0000 "Basic", attribute 0x00004 and 0x0005

**Comment by SimoBa80** [comment]
> Nope, the missing information is "Model identifier", to reconise device deconz use it and the "Manufacturer", on the 2 capture you have "unknow". This is something normal on battery device, because they are sleeper, you need to awake them in same time you ask for attribute"
> 
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters
> 
> The usefull one are in cluster 0x0000 "Basic", attribute 0x00004 and 0x0005

Thanks for the Hint i am new to deconz:
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/163328007/3be0491c-4c82-40da-9c02-7fb73fff1beb)

I have also tried with the Json File you provided but nothing happens in Phoscon App.

Many Thanks and Regards
Simon

**Comment by SimoBa80** [comment]
![20240326_125054](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/163328007/bcde2441-7cbd-445b-a888-db76aca5b8fa)

**Comment by Smanar** [comment]
So I m sorry, but this device can't be used with deconz.
If you look at the capture, it's same result, the attribute 0x0005 is empty, not possible to do something with this device.

**Comment by SimoBa80** [comment]
ok that is bad but ok, so i need to have some new sensors. 
Ok there is also nothing which would this device work?

**Comment by Smanar** [comment]
No sorry, deconz use the manufacture name and the model id to reconise device, if one of them is missing, not possible. Deconz need both.

**Comment by Little-Foxy** [comment]
I got one of these as well with an empty Model identifier. Values like temp, etc are still reported in the cluster in the gui though. Is there no way to read these values out from an 'unidentified' device via API? Reading the mac address via api just returns a mostly empty object. Or force a device to use a ddf file manually?

**Comment by Smanar** [comment]
Deconz reconise device using the couple Model ID/ Manufacture name to use DDF.
So without one of them, not posible ATM.
