### ISSUE TITLE
Deconz: failed to open DDF 

### ISSUE THREAD

**Issue by pimw1** [dresden-elektronik/deconz-rest-plugin#7971]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

When pressing control-e to open the DDF editor, followed by control-o, selecting the appropiate json.file, the following message appears: failed to open xxxxx.json

The DDF will be loaded by either choosing "Hot reload"  or by restarting the deconz docker container.

### Steps to reproduce the behavior

1. select a device
2. control-e
3. control-o
4. select the appropiate .json file
5. observe the error
6. control-r to hot reload the DDF

### Expected behavior

1. select a device
2. control-e
3. control-o
4. select the appropiate .json file
5. not giving an error but either "auto-hot reload" for me or display an info message that i should hot-reload

### Environment

- Host system: Proxmox NAS, running a Ubuntu VM
- Running method: deconz-docker container
- Firmware version: 26780700
- deCONZ version: 2.29.0
- Device: ConBee II (connected via USB 2)
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? 2x HDD via USB 3

**Comment by Subnum12** [comment]
👍   same issue
also if you save a custom DDF, you cannot open it anymore. No error in log btw.

![grafik](https://github.com/user-attachments/assets/f676257e-e90b-41e1-8d43-cbf709a90bbc)

also [documentation ](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#precedence-of-ddf-files) seems incorrect.
>directory of the user running deCONZ (e.g. `/home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices`) should be `/home/<DECONZUSER>/.local/share/deCONZ/devices`

**Comment by pimw1** [comment]
Given the lack of response, i think this has no priority for Dresden Elektronic. Therefore, i am closing this issue.

**Comment by kimchiii0411** [comment]
I'm having the same issue. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8048

**Comment by dustnipe** [comment]
me too :(

**Comment by Smanar** [comment]
Wich one DDF are you trying to open ? Officiel one or custom one ?

**Comment by Daad66** [comment]
Same here ... 
Running deconz in docker container (runnig since years like a charm! ;-) )
Now, I can't open **any** DDF file anymore from the X11 gui. Neither from /opt/deCONZ/devices nor from /usr/share/deCONZ/devices.
The file permissions are all OK and I can cat them from shell as deconz user. 
Seems to be something in the open processing routine (just a guess) 
Best 
Detlef

**Comment by Daad66** [comment]
As I could't open an existing DDF to assign it to a new sensor I just created a new one for it. Tis works so far ... but I recognized that the new DDF file has "^M" at all line ends. --> is the root cause maybe a Linux / Windows file format mismatch? 
This would explain the "Failed to open  ... .json " errors... 
Is the expected platform (windows / linux) configurable somewhere ?
Best
Detlef

**Comment by Daad66** [comment]
Just to prove my theory I converted the corresponding DDF json file on /opt/deCONZ/devices to Windows File Format (with CRLF) and ... it works ! The new open/close sensor is now automatically recognized without problem :-) 
I still can not open the DDF file via Edit DDF -> File ->open     but at least I got the sensor running by converting the DDF to Windows file format.
Hope that helps to find the root cause.

**Comment by Smanar** [comment]
But I don't see what you machine can have, and other haven't ?
Lot of users are using the deconz docker without issue.

A special setting on dockers ?

**Comment by Smanar** [comment]
Ok, have the same issue
Not possible to load DDF, I need to restart deconz, and ofc deconz is hanging https://forum.phoscon.de/t/cannot-stop-deconz-via-systemctl/6723/12

Version 2.32.4 beta
