### ISSUE TITLE
Moes AM43 Blind Drive Motor _TZE200_icka1clh

### ISSUE THREAD

**Issue by tobiasr19** [dresden-elektronik/deconz-rest-plugin#7990]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

ZigBee AM43 Blind Drive Motor

### Manufacturer

_TZE200_icka1clh

### Model identifier

TS0601

### Device type to add

Other

### Node info

![grafik](https://github.com/user-attachments/assets/eb1d67f1-4bcf-4473-b5a0-ea130d4910b8)

### Endpoints and clusters

![grafik](https://github.com/user-attachments/assets/f23ac3c7-6c5a-4e2e-ba55-b7242cc4b912)

### Basic

![grafik](https://github.com/user-attachments/assets/395c80d2-fb31-48e2-8d62-4224859c7983)

### Further relevant clusters

Maybe similar to [issues/4521](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4521)

**Comment by unix9t9** [comment]
I also have bought These Moes am43 Blinds Drive because the blakadder repository said it should work with deCONZ. Mine have another Manufakturer. It is: _TZE200_zah67ekd. The rest seems to bei the same like tobiasr19 blinds driver. My motors are recognized as a battery sensor. Repairing without deleting the node or reading the Basic Cluster or reading the node and simple discriptors hast no effect. Maybe someone can make a ddf for it?
<img width="423" alt="BasicCluster1" src="https://github.com/user-attachments/assets/2d488f83-b8b9-4ba7-a0dd-af09bd90caf8">
<img width="421" alt="BasicCluster2" src="https://github.com/user-attachments/assets/0ecd7f72-d356-426e-9e5e-988f7b8ea202">
<img width="419" alt="BasicCluster3" src="https://github.com/user-attachments/assets/c0dc517e-e505-45e3-98d5-3a47add19140">
<img width="262" alt="Node" src="https://github.com/user-attachments/assets/23a585e5-1753-4c91-9a3f-aa73de20fcb4">
<img width="428" alt="NodeInfo1" src="https://github.com/user-attachments/assets/8ddea413-9d9d-4370-bfe3-7ea14f76e32f">
<img width="431" alt="NodeInfo2" src="https://github.com/user-attachments/assets/873c99fb-6023-49aa-b98a-ef365881c269">

**Comment by tobiasr19** [comment]
It works out of the box with zigbee2mqtt. Change from deconz to zigbee2mqtt was my solution.

**Comment by Smanar** [comment]
`    {"_TZE200_zah67ekd", "TS0601", "MoesHouse / Livolo", "Tuya_COVD AM43-0.45-40"},`

This one is working natively on deconz, I don't remember the procedure to include it, but you have it on a post on the forum less than 1 month ago.

**Comment by unix9t9** [comment]
> ` {"_TZE200_zah67ekd", "TS0601", "MoesHouse / Livolo", "Tuya_COVD AM43-0.45-40"},`
> 
> This one is working natively on deconz, I don't remember the procedure to include it but you can try that to start #7958
> 
> or
> 
> > You need to incluse two Times first in phoscon, and the second Time, in deconz, you need to enable joint and press right click on the module and Made the actions 1, 7 and 8 (in the joint Time)

Thank you. I will try IT the next days... What du you mean with making the actions 1 7 and 8? Alt + Cntrl + 1 or 7 or 8?

**Comment by unix9t9** [comment]
I tried to pair the blind Drivers as you descriped it. But it hast no effect. The node stays a battery sensor. There is No new entry in the API created. I tried it several times. I also paired it twice without deleting the node. But nothing happened.

**Comment by Smanar** [comment]
Honneslty I don't remember the procedure, you have tried with deleting the battery entry ?
You don't have access to the GUI ? It's easier to force the inclusion with it.

**Comment by unix9t9** [comment]
I have Access to the GUI.I deleted the node. Repaired IT twice an tried to do the shortcut thing you discribed. But no Chance. Maybe i try IT again tomorrow

**Comment by unix9t9** [comment]
I got it. The Solution was do restart the Gateway after pairing and set it Info permit Join again. Then read the discriptors.

**Comment by unix9t9** [comment]
Is there a possibility so read the battery Status of the Blinds driver?

**Comment by Smanar** [comment]
The ZHABattery device is not created this time ?

**Comment by unix9t9** [comment]
It ist created, but it sends no Status. It ist Always NULL
